// ═══ TCM_MODEL · Auto-generated 2026-07-21 ═══
// DO NOT EDIT - This file is generated by kb-management-engine.js
// Source: formal_knowledge table → knowledge_models table

const TCM_MODEL = {
  module: "tcm",
  version: "v1",
  updated_at: "2026-07-21T14:41:01.744Z",

  entries: {
  "KB-CASE-001": {
    "tags": [
      "湿",
      "体质",
      "脾",
      "虚"
    ],
    "confidence": 0.95,
    "category": "临床案例蒸馏",
    "difficulty": "advanced",
    "access_level": "professional",
    "summary": "日主戊土生于辰月，土旺但湿气重，脾失健运。需健脾祛湿、理气和中。...",
    "content": "enc:6e3fcae8e7aa543ff408836809359d91:80f25b938f41242c73179aead4da5cf7:d9074b67a74c191e7f6f2343cf9a84f6123ca310ef159f4385a2762970dae85b7f4008063077d0f17c3c53edc203de35422f1454031db841f8b0afce836a29807e42b584a6797e3e8c36b88aabf0846bfd7320af424c48632f10028b66fe2c38",
    "source_ids": [
      "SRC-CASE-003"
    ]
  },
  "KB-CASE-002": {
    "tags": [
      "寒",
      "体质",
      "肾"
    ],
    "confidence": 0.95,
    "category": "临床案例蒸馏",
    "difficulty": "advanced",
    "access_level": "professional",
    "summary": "日主丙火生于子月，水旺火灭，肾阳被寒水所困。需调候温阳，补命门之火。...",
    "content": "enc:e22fb62f1adadcab2659a17095c8d86d:3d870be1cbb48ca52c8abf8f3104f1c1:4f81f61a0f2aa67f169c93c11d6c75374dfe0cb6c4e616878a985f35a6eb25e2af856cb7b7344ce1e329837bb35d8f0e010d767e717fd089c17569736d94658120e9f111869caae5670667811ff02cba3a1b371e1ff1803fca6058d6771171d1ec22aa2da411",
    "source_ids": [
      "SRC-CASE-002"
    ]
  },
  "KB-CASE-003": {
    "tags": [
      "体质",
      "肝"
    ],
    "confidence": 0.95,
    "category": "临床案例蒸馏",
    "difficulty": "advanced",
    "access_level": "professional",
    "summary": "日主癸水生于午月，火旺水弱，肝木受火克伐。大运乙丑湿土扶身，但丑未冲激，情绪波动大。建议疏肝理气、滋...",
    "content": "enc:3bcf72d861f0b865147a9d4a8c611995:729062c83eca20701c9ca825cf91e03a:d860e48f7491b8470390934b3793c349e776d9e57a8a546722cd8e20155e6a69441e24b6b03f8f69c97e6788a55a2449849c3209df7a82822f99302fec63131c013c580258d08c28084791a5a941400586943d7e8b6a0b901920800351bcc3a99fff009c5d875b07bc9242aa4425f26959a0547d5c2849a1ff54c76cecdb5f7cdf37260ce0efaaee97ecf742f295155d035de88439d1e7ae8378bb01c6e26594db63",
    "source_ids": [
      "SRC-CASE-001"
    ]
  }
},

  inverted_index: {
  "湿": [
    "KB-CASE-001"
  ],
  "体质": [
    "KB-CASE-001",
    "KB-CASE-002",
    "KB-CASE-003"
  ],
  "脾": [
    "KB-CASE-001"
  ],
  "虚": [
    "KB-CASE-001"
  ],
  "寒": [
    "KB-CASE-002"
  ],
  "肾": [
    "KB-CASE-002"
  ],
  "肝": [
    "KB-CASE-003"
  ]
},

  categories: {
  "临床案例蒸馏": [
    "KB-CASE-001",
    "KB-CASE-002",
    "KB-CASE-003"
  ]
},

  /**
   * 按关键词搜索（标签匹配）
   */
  search(query) {
    if (!query) return [];
    const words = query.split(/[\s,，、]+/).filter(w => w.length > 0);
    const scored = {};
    for (const word of words) {
      for (const [tag, ids] of Object.entries(this.inverted_index)) {
        if (tag.includes(word) || word.includes(tag)) {
          for (const id of ids) {
            scored[id] = (scored[id] || 0) + 1;
          }
        }
      }
    }
    return Object.entries(scored)
      .sort((a, b) => b[1] - a[1])
      .map(([id, score]) => ({ entry_id: id, score, ...this.entries[id] }))
      .filter(e => e.content);
  },

  /**
   * 按分类获取
   */
  byCategory(cat) {
    const ids = this.categories[cat] || [];
    return ids.map(id => ({ entry_id: id, ...this.entries[id] })).filter(e => e.content);
  },

  /**
   * 按标签获取
   */
  byTag(tag) {
    const ids = this.inverted_index[tag] || [];
    return ids.map(id => ({ entry_id: id, ...this.entries[id] })).filter(e => e.content);
  },

  /**
   * 追溯来源
   */
  traceSource(entry_id) {
    const e = this.entries[entry_id];
    if (!e || !e.source_ids) return [];
    return e.source_ids;
  },

  /**
   * 统计
   */
  stats() {
    return {
      module: this.module,
      version: this.version,
      entry_count: Object.keys(this.entries).length,
      tag_count: Object.keys(this.inverted_index).length,
      category_count: Object.keys(this.categories).length,
    };
  }
};

// 挂到全局
try { window.TCM_MODEL = TCM_MODEL; } catch(e) {}
try { module.exports = TCM_MODEL; } catch(e) {}
