// ═══ ZIWEI_MODEL · Auto-generated 2026-07-22 ═══
// DO NOT EDIT - This file is generated by kb-management-engine.js
// Source: kb_formal table → knowledge_models table

const ZIWEI_MODEL = {
  module: "ziwei",
  version: "v1",
  updated_at: "2026-07-22T02:42:57.982Z",

  entries: {
  "KB-ziwei-00700": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫微斗数以紫微星（北极星）为众星之主，结合古人所观测的南北斗诸星，构建了一个包含一百多颗星曜的命理体系。",
    "content": "紫微斗数以紫微星（北极星）为众星之主，结合古人所观测的南北斗诸星，构建了一个包含一百多颗星曜的命理体系。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00701": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "传承方向：陈抟创法 → 明代罗洪先增修 → 清代周亮增等整理 → 民国时期流传至台湾 → 现代在华人世界广泛流行。",
    "content": "传承方向：陈抟创法 → 明代罗洪先增修 → 清代周亮增等整理 → 民国时期流传至台湾 → 现代在华人世界广泛流行。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00702": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫微斗数的独特之处在于将命盘分为十二宫，每宫对应人生不同领域，通过星曜组合、四化、三方四正等判断吉凶，其特点是「星曜丰富，系统庞大」。",
    "content": "紫微斗数的独特之处在于将命盘分为十二宫，每宫对应人生不同领域，通过星曜组合、四化、三方四正等判断吉凶，其特点是「星曜丰富，系统庞大」。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00703": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫微斗数的独特之处在于将命盘分为十二宫，每宫对应人生不同领域，通过星曜组合、四化、三方四正等判断吉凶，其特点是「星曜丰富，系统庞大」。",
    "content": "紫微斗数的独特之处在于将命盘分为十二宫，每宫对应人生不同领域，通过星曜组合、四化、三方四正等判断吉凶，其特点是「星曜丰富，系统庞大」。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00704": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "content": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00705": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "content": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00706": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "content": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00707": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "content": "命宫、财帛宫、官禄宫为三方（三合），加上迁移宫为四正。此四宫之间存在生克关系，是紫微斗数最重要的概念之一。三方吉拱，福禄双全；三方煞凑，一生坎坷。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00708": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫微斗数中的星曜分甲级（14主星）、乙级（80+辅星）、丙级星，共107颗。另有流曜如流昌、流曲、流魁、流钺及四化引动。",
    "content": "紫微斗数中的星曜分甲级（14主星）、乙级（80+辅星）、丙级星，共107颗。另有流曜如流昌、流曲、流魁、流钺及四化引动。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00709": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "星曜在不同宫位有庙（最强）、旺（次强）、平（中和）、陷（最弱）四种状态。庙则吉祥加倍，陷则凶性彰显。此乃断盘要诀。",
    "content": "星曜在不同宫位有庙（最强）、旺（次强）、平（中和）、陷（最弱）四种状态。庙则吉祥加倍，陷则凶性彰显。此乃断盘要诀。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00710": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "星曜在不同宫位有庙（最强）、旺（次强）、平（中和）、陷（最弱）四种状态。庙则吉祥加倍，陷则凶性彰显。此乃断盘要诀。",
    "content": "星曜在不同宫位有庙（最强）、旺（次强）、平（中和）、陷（最弱）四种状态。庙则吉祥加倍，陷则凶性彰显。此乃断盘要诀。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00711": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主贵气，三方吉拱则富贵双全；入财帛主以权力获财；入官禄主居高位掌权；入夫妻宫主配偶有地位但关系疏离；入疾厄宫主脾胃之疾；入迁移宫主出外得人尊重。",
    "content": "入命宫主贵气，三方吉拱则富贵双全；入财帛主以权力获财；入官禄主居高位掌权；入夫妻宫主配偶有地位但关系疏离；入疾厄宫主脾胃之疾；入迁移宫主出外得人尊重。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00712": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主贵气，三方吉拱则富贵双全；入财帛主以权力获财；入官禄主居高位掌权；入夫妻宫主配偶有地位但关系疏离；入疾厄宫主脾胃之疾；入迁移宫主出外得人尊重。",
    "content": "入命宫主贵气，三方吉拱则富贵双全；入财帛主以权力获财；入官禄主居高位掌权；入夫妻宫主配偶有地位但关系疏离；入疾厄宫主脾胃之疾；入迁移宫主出外得人尊重。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00713": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫微+天府=紫府同宫，终身福厚；紫微+七杀=权威魄力开拓；紫微+贪狼=桃花犯主；紫微+天相=禄权科会大贵；紫微+破军=动荡不安。",
    "content": "紫微+天府=紫府同宫，终身福厚；紫微+七杀=权威魄力开拓；紫微+贪狼=桃花犯主；紫微+天相=禄权科会大贵；紫微+破军=动荡不安。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00714": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主心思缜密，机变迅捷，善谋略；入兄弟宫主兄弟有智谋；入夫妻宫主配偶聪明但易变；入财帛主智慧取财但财来财去；入官禄主谋划型职业如军师、策划、工程师。",
    "content": "入命宫主心思缜密，机变迅捷，善谋略；入兄弟宫主兄弟有智谋；入夫妻宫主配偶聪明但易变；入财帛主智慧取财但财来财去；入官禄主谋划型职业如军师、策划、工程师。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00715": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主心思缜密，机变迅捷，善谋略；入兄弟宫主兄弟有智谋；入夫妻宫主配偶聪明但易变；入财帛主智慧取财但财来财去；入官禄主谋划型职业如军师、策划、工程师。",
    "content": "入命宫主心思缜密，机变迅捷，善谋略；入兄弟宫主兄弟有智谋；入夫妻宫主配偶聪明但易变；入财帛主智慧取财但财来财去；入官禄主谋划型职业如军师、策划、工程师。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00716": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主心思缜密，机变迅捷，善谋略；入兄弟宫主兄弟有智谋；入夫妻宫主配偶聪明但易变；入财帛主智慧取财但财来财去；入官禄主谋划型职业如军师、策划、工程师。",
    "content": "入命宫主心思缜密，机变迅捷，善谋略；入兄弟宫主兄弟有智谋；入夫妻宫主配偶聪明但易变；入财帛主智慧取财但财来财去；入官禄主谋划型职业如军师、策划、工程师。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00717": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "天机+太阴=机月同梁格（加天同、天梁），为吏人结构；天机+巨门=口舌争辩；天机+天梁=善谈兵法军机。",
    "content": "天机+太阴=机月同梁格（加天同、天梁），为吏人结构；天机+巨门=口舌争辩；天机+天梁=善谈兵法军机。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00718": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "content": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00719": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "content": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00720": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "content": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00721": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "content": "入命宫主性格开朗，热心公益，但夜生人太阳无光则劳碌；入财帛主光明正大赚钱，不喜暗昧之财；入夫妻宫主配偶性格开朗但有刺眼之嫌；入官禄主公职、政治、公众事业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00722": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "太阳+天梁+文昌+化禄=阳梁昌禄格，考试夺魁；太阳+巨门=口舌是非但可化解黑暗；太阳+太阴（同宫或对拱）=日月并明大格。",
    "content": "太阳+天梁+文昌+化禄=阳梁昌禄格，考试夺魁；太阳+巨门=口舌是非但可化解黑暗；太阳+太阴（同宫或对拱）=日月并明大格。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00723": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格刚直，有领导才能和执行力；入财帛正财星，主金融、制造业获利；入夫妻宫主配偶能力强但性格刚硬；入官禄主金融、军警、工科等职业。",
    "content": "入命宫主性格刚直，有领导才能和执行力；入财帛正财星，主金融、制造业获利；入夫妻宫主配偶能力强但性格刚硬；入官禄主金融、军警、工科等职业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00724": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格刚直，有领导才能和执行力；入财帛正财星，主金融、制造业获利；入夫妻宫主配偶能力强但性格刚硬；入官禄主金融、军警、工科等职业。",
    "content": "入命宫主性格刚直，有领导才能和执行力；入财帛正财星，主金融、制造业获利；入夫妻宫主配偶能力强但性格刚硬；入官禄主金融、军警、工科等职业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00725": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格刚直，有领导才能和执行力；入财帛正财星，主金融、制造业获利；入夫妻宫主配偶能力强但性格刚硬；入官禄主金融、军警、工科等职业。",
    "content": "入命宫主性格刚直，有领导才能和执行力；入财帛正财星，主金融、制造业获利；入夫妻宫主配偶能力强但性格刚硬；入官禄主金融、军警、工科等职业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00726": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "武曲+天府=财库充实；武曲+贪狼=武贪不发少年人，晚发之格；武曲+七杀=大起大落；武曲+破军=钱财耗散。",
    "content": "武曲+天府=财库充实；武曲+贪狼=武贪不发少年人，晚发之格；武曲+七杀=大起大落；武曲+破军=钱财耗散。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00727": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主人际关系好，性格温和，知足常乐；入财帛主不愁钱财但非大富；入夫妻宫主婚姻和谐美满；入福德宫主精神享受丰富。",
    "content": "入命宫主人际关系好，性格温和，知足常乐；入财帛主不愁钱财但非大富；入夫妻宫主婚姻和谐美满；入福德宫主精神享受丰富。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00728": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主人际关系好，性格温和，知足常乐；入财帛主不愁钱财但非大富；入夫妻宫主婚姻和谐美满；入福德宫主精神享受丰富。",
    "content": "入命宫主人际关系好，性格温和，知足常乐；入财帛主不愁钱财但非大富；入夫妻宫主婚姻和谐美满；入福德宫主精神享受丰富。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00729": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主人际关系好，性格温和，知足常乐；入财帛主不愁钱财但非大富；入夫妻宫主婚姻和谐美满；入福德宫主精神享受丰富。",
    "content": "入命宫主人际关系好，性格温和，知足常乐；入财帛主不愁钱财但非大富；入夫妻宫主婚姻和谐美满；入福德宫主精神享受丰富。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00730": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "天同+太阴=同阴在子，福寿绵长；天同+巨门=同巨在丑未，口舌是非多；天同+天梁=同梁在寅申，清闲之福。",
    "content": "天同+太阴=同阴在子，福寿绵长；天同+巨门=同巨在丑未，口舌是非多；天同+天梁=同梁在寅申，清闲之福。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00731": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主聪明但性格复杂，善恶一念之间；入夫妻宫次桃花，感情丰富但多波折；入官禄主与法律、监察相关职业；入疾厄主血液、心脏疾病。",
    "content": "入命宫主聪明但性格复杂，善恶一念之间；入夫妻宫次桃花，感情丰富但多波折；入官禄主与法律、监察相关职业；入疾厄主血液、心脏疾病。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00732": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主聪明但性格复杂，善恶一念之间；入夫妻宫次桃花，感情丰富但多波折；入官禄主与法律、监察相关职业；入疾厄主血液、心脏疾病。",
    "content": "入命宫主聪明但性格复杂，善恶一念之间；入夫妻宫次桃花，感情丰富但多波折；入官禄主与法律、监察相关职业；入疾厄主血液、心脏疾病。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00733": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主聪明但性格复杂，善恶一念之间；入夫妻宫次桃花，感情丰富但多波折；入官禄主与法律、监察相关职业；入疾厄主血液、心脏疾病。",
    "content": "入命宫主聪明但性格复杂，善恶一念之间；入夫妻宫次桃花，感情丰富但多波折；入官禄主与法律、监察相关职业；入疾厄主血液、心脏疾病。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00734": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "廉贞+天府=廉府在辰戌，稳重中含变化；廉贞+贪狼=桃花泛滥；廉贞+七杀=路上埋尸，大凶之格；廉贞+破军=刑囚耗，凶险。",
    "content": "廉贞+天府=廉府在辰戌，稳重中含变化；廉贞+贪狼=桃花泛滥；廉贞+七杀=路上埋尸，大凶之格；廉贞+破军=刑囚耗，凶险。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00735": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主稳重踏实，晚年富足，心地仁厚；入财帛守财之库，主积聚财富；入田宅主房产丰厚；入官禄主管理型领导。",
    "content": "入命宫主稳重踏实，晚年富足，心地仁厚；入财帛守财之库，主积聚财富；入田宅主房产丰厚；入官禄主管理型领导。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00736": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主稳重踏实，晚年富足，心地仁厚；入财帛守财之库，主积聚财富；入田宅主房产丰厚；入官禄主管理型领导。",
    "content": "入命宫主稳重踏实，晚年富足，心地仁厚；入财帛守财之库，主积聚财富；入田宅主房产丰厚；入官禄主管理型领导。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00737": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主稳重踏实，晚年富足，心地仁厚；入财帛守财之库，主积聚财富；入田宅主房产丰厚；入官禄主管理型领导。",
    "content": "入命宫主稳重踏实，晚年富足，心地仁厚；入财帛守财之库，主积聚财富；入田宅主房产丰厚；入官禄主管理型领导。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00738": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "天府+紫微=紫府同宫，终身福厚；天府+武曲=财库充实；天府+廉贞=廉府在辰戌，贵格；天府朝垣（三方有天相）=府相朝垣格。",
    "content": "天府+紫微=紫府同宫，终身福厚；天府+武曲=财库充实；天府+廉贞=廉府在辰戌，贵格；天府朝垣（三方有天相）=府相朝垣格。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00739": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格内敛，有艺术气质，女性尤吉；入财帛主以耐心理财积蓄致富；入夫妻宫主配偶温柔体贴；入田宅主有好的居家环境。",
    "content": "入命宫主性格内敛，有艺术气质，女性尤吉；入财帛主以耐心理财积蓄致富；入夫妻宫主配偶温柔体贴；入田宅主有好的居家环境。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00740": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格内敛，有艺术气质，女性尤吉；入财帛主以耐心理财积蓄致富；入夫妻宫主配偶温柔体贴；入田宅主有好的居家环境。",
    "content": "入命宫主性格内敛，有艺术气质，女性尤吉；入财帛主以耐心理财积蓄致富；入夫妻宫主配偶温柔体贴；入田宅主有好的居家环境。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00741": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主性格内敛，有艺术气质，女性尤吉；入财帛主以耐心理财积蓄致富；入夫妻宫主配偶温柔体贴；入田宅主有好的居家环境。",
    "content": "入命宫主性格内敛，有艺术气质，女性尤吉；入财帛主以耐心理财积蓄致富；入夫妻宫主配偶温柔体贴；入田宅主有好的居家环境。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00742": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "太阴+天同=同阴在子，福寿之格；太阴+天机=机阴在寅申，策划能力佳；太阴+太阳（对拱）=日月并明或日月反背。",
    "content": "太阴+天同=同阴在子，福寿之格；太阴+天机=机阴在寅申，策划能力佳；太阴+太阳（对拱）=日月并明或日月反背。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00743": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "入命宫主多才多艺、桃花旺盛、善交际；入夫妻宫主配偶相貌佳但桃花多；入财帛主偏财运强，善投机；入福德主追求享乐。",
    "content": "入命宫主多才多艺、桃花旺盛、善交际；入夫妻宫主配偶相貌佳但桃花多；入财帛主偏财运强，善投机；入福德主追求享乐。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00744": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫府入命者一生安稳富足，格局宏大，有领导才能和包容力。适合从政、管理、金融等需要权钱双收的行业。但过于安稳也可能缺乏突破力，需要适当的挑战以激发潜能。",
    "content": "紫府入命者一生安稳富足，格局宏大，有领导才能和包容力。适合从政、管理、金融等需要权钱双收的行业。但过于安稳也可能缺乏突破力，需要适当的挑战以激发潜能。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00745": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "财帛宫紫府为最佳配置之一，主钱财有权有势亦有库。赚钱能力和社会地位相匹配，财富积累稳健。善于利用权力和资源换取财富。收入来源稳定且体面。",
    "content": "财帛宫紫府为最佳配置之一，主钱财有权有势亦有库。赚钱能力和社会地位相匹配，财富积累稳健。善于利用权力和资源换取财富。收入来源稳定且体面。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00746": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫府在官禄宫者事业有权威且稳定，是典型的大企业高管或政府高官的命格。事业上升路径清晰，有贵人相助，适合大型组织的管理层。事业有成且受尊重。",
    "content": "紫府在官禄宫者事业有权威且稳定，是典型的大企业高管或政府高官的命格。事业上升路径清晰，有贵人相助，适合大型组织的管理层。事业有成且受尊重。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00747": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "夫妻宫紫府者配偶既有社会地位也有经济实力，婚姻门当户对。但夫妻关系偏「政治婚姻」型，感情可能不如利益契合来得重要。婚姻中需培养共同的兴趣和情感连接。",
    "content": "夫妻宫紫府者配偶既有社会地位也有经济实力，婚姻门当户对。但夫妻关系偏「政治婚姻」型，感情可能不如利益契合来得重要。婚姻中需培养共同的兴趣和情感连接。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00748": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫杀同宫为威权之格。紫微之尊与七杀之勇结合，如帝王身边的猛将。此组合之人性格刚烈果敢、权威开拓，适合创业、从军、从政等需要魄力的领域。一生变化极大，不破不立。",
    "content": "紫杀同宫为威权之格。紫微之尊与七杀之勇结合，如帝王身边的猛将。此组合之人性格刚烈果敢、权威开拓，适合创业、从军、从政等需要魄力的领域。一生变化极大，不破不立。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00749": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫杀入命者敢于开拓，有领袖气质和决断力。但性格过于刚硬，需要左辅右弼来调和。一生大起大落，不宜安逸，越有挑战越精彩。为人处事果断，但需注意人际关系。",
    "content": "紫杀入命者敢于开拓，有领袖气质和决断力。但性格过于刚硬，需要左辅右弼来调和。一生大起大落，不宜安逸，越有挑战越精彩。为人处事果断，但需注意人际关系。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00750": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫杀在财帛者赚钱方式大胆，敢做高风险高回报的投资。财运起伏大，可能富可敌国也可能一朝返贫。需要专业的财务团队辅助，不可单打独斗。",
    "content": "紫杀在财帛者赚钱方式大胆，敢做高风险高回报的投资。财运起伏大，可能富可敌国也可能一朝返贫。需要专业的财务团队辅助，不可单打独斗。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00751": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫杀在官禄为开拓型事业运。适合创业当老板或做高管，适合军警、地产、建筑等需要强执行力的行业。事业有开疆拓土之势，但守成阶段需要调整策略。",
    "content": "紫杀在官禄为开拓型事业运。适合创业当老板或做高管，适合军警、地产、建筑等需要强执行力的行业。事业有开疆拓土之势，但守成阶段需要调整策略。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00752": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫杀在夫妻者婚姻中有激烈的权力斗争。双方性格都刚硬，需要磨合。婚姻进展快但风险大，适合晚婚。配偶也是强势人物，互相尊重和理解是婚姻的关键。",
    "content": "紫杀在夫妻者婚姻中有激烈的权力斗争。双方性格都刚硬，需要磨合。婚姻进展快但风险大，适合晚婚。配偶也是强势人物，互相尊重和理解是婚姻的关键。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00753": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫破同宫主动荡不安。紫微之尊与破军之耗结合，如帝王身边出了个不安分的改革者。此组合之人一生充满变故，有不断打破重建的倾向。命运如潮水，有起有落，适合从事变革和创...",
    "content": "紫破同宫主动荡不安。紫微之尊与破军之耗结合，如帝王身边出了个不安分的改革者。此组合之人一生充满变故，有不断打破重建的倾向。命运如潮水，有起有落，适合从事变革和创新类工作。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00754": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫破在官禄者事业多变，不适合稳定工作。适合创业者和改革者，在动荡中寻找机会。事业如同冲浪，每次浪来都有新的可能。适合新兴行业和变革期的产业。",
    "content": "紫破在官禄者事业多变，不适合稳定工作。适合创业者和改革者，在动荡中寻找机会。事业如同冲浪，每次浪来都有新的可能。适合新兴行业和变革期的产业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00755": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫破在夫妻者婚姻多变不稳定。夫妻关系如过山车，高时极高低时极低。早婚不太适合，晚婚或有多次婚姻经历后更懂得珍惜。婚姻需要极大的包容和弹性。",
    "content": "紫破在夫妻者婚姻多变不稳定。夫妻关系如过山车，高时极高低时极低。早婚不太适合，晚婚或有多次婚姻经历后更懂得珍惜。婚姻需要极大的包容和弹性。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00756": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫贪同宫即「桃花犯主」格。紫微之尊贵与贪狼之欲望结合，如同帝王沉迷美色。此组合之人才华横溢但需克制欲望，否则贵人身份被欲望侵蚀。人生精彩但充满诱惑。",
    "content": "紫贪同宫即「桃花犯主」格。紫微之尊贵与贪狼之欲望结合，如同帝王沉迷美色。此组合之人才华横溢但需克制欲望，否则贵人身份被欲望侵蚀。人生精彩但充满诱惑。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00757": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫贪入命者多才多艺，有领袖魅力，但桃花极重。才华和欲望并存，需自我约束。适合演艺、艺术、公关等需要魅力的行业。为人有趣味但需守住底线，不可沉溺欲望。",
    "content": "紫贪入命者多才多艺，有领袖魅力，但桃花极重。才华和欲望并存，需自我约束。适合演艺、艺术、公关等需要魅力的行业。为人有趣味但需守住底线，不可沉溺欲望。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00758": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫贪在财帛者财源广且善于交际应酬赚钱。偏财运强，适合娱乐、时尚、奢侈品等行业。但花钱也大手大脚，需要节制。财运多与人际关系相关。",
    "content": "紫贪在财帛者财源广且善于交际应酬赚钱。偏财运强，适合娱乐、时尚、奢侈品等行业。但花钱也大手大脚，需要节制。财运多与人际关系相关。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00759": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫贪在官禄者事业多有贵人提携但因桃花或人际问题而有波折。适合需要社交能力的行业。事业上容易因男女关系而受影响，需公私分明、洁身自好。",
    "content": "紫贪在官禄者事业多有贵人提携但因桃花或人际问题而有波折。适合需要社交能力的行业。事业上容易因男女关系而受影响，需公私分明、洁身自好。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00760": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "紫贪在夫妻者配偶魅力大但桃花极重，婚姻多有第三者困扰。婚前情史丰富，婚后需格外经营。配偶可能是众人瞩目的对象，需要充分的信任和沟通。",
    "content": "紫贪在夫妻者配偶魅力大但桃花极重，婚姻多有第三者困扰。婚前情史丰富，婚后需格外经营。配偶可能是众人瞩目的对象，需要充分的信任和沟通。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00761": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机阴同宫为「机月」组合的基础。天机之智与太阴之柔结合，聪明而细腻。此组合之人善于策划和细节把控，适合策划、财务、资讯类工作。加天同天梁则成大名鼎鼎的机月同梁格。",
    "content": "机阴同宫为「机月」组合的基础。天机之智与太阴之柔结合，聪明而细腻。此组合之人善于策划和细节把控，适合策划、财务、资讯类工作。加天同天梁则成大名鼎鼎的机月同梁格。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00762": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机阴入命者心思缜密，善于分析和规划。性格偏内向细腻，做事有条理。机关算尽但有时过于多虑而错失行动时机。需要培养决策的果断力，平衡思考与行动。",
    "content": "机阴入命者心思缜密，善于分析和规划。性格偏内向细腻，做事有条理。机关算尽但有时过于多虑而错失行动时机。需要培养决策的果断力，平衡思考与行动。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00763": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机阴在财帛者以智慧和耐心赚钱。善于理财规划，能精打细算。适合做会计、投资顾问、精算师等需要精密计算的职业。财运稳定，但需要主动把握机会。",
    "content": "机阴在财帛者以智慧和耐心赚钱。善于理财规划，能精打细算。适合做会计、投资顾问、精算师等需要精密计算的职业。财运稳定，但需要主动把握机会。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00764": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机阴在官禄者适合脑力劳动和精细化工作。事业上善于策略，适合做策划、咨询、研究。但可能过于谨慎而缺乏突破力。在稳定环境中才能发挥最大优势。",
    "content": "机阴在官禄者适合脑力劳动和精细化工作。事业上善于策略，适合做策划、咨询、研究。但可能过于谨慎而缺乏突破力。在稳定环境中才能发挥最大优势。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00765": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机阴在夫妻者婚姻以理性和细腻的沟通为主。夫妻间互相理解，善于照顾对方的情绪。但有时过于分析关系反而少了感性。需要给婚姻加入浪漫和惊喜。",
    "content": "机阴在夫妻者婚姻以理性和细腻的沟通为主。夫妻间互相理解，善于照顾对方的情绪。但有时过于分析关系反而少了感性。需要给婚姻加入浪漫和惊喜。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00766": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨机同宫为「巨机同宫格」。天机之智与巨门之口结合，口才与智慧并存。此组合之人善于辩论分析，但也容易惹口舌是非。适合律师、咨询、媒体等需要犀利言辞的行业。",
    "content": "巨机同宫为「巨机同宫格」。天机之智与巨门之口结合，口才与智慧并存。此组合之人善于辩论分析，但也容易惹口舌是非。适合律师、咨询、媒体等需要犀利言辞的行业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00767": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨机入命者能言善辩，思维敏捷，善于发现问题的关键。但说话过于犀利容易得罪人。适合做律师、评论家、谈判专家。为人精明但人缘需注意维护。学会在适当的时候保持沉默是重...",
    "content": "巨机入命者能言善辩，思维敏捷，善于发现问题的关键。但说话过于犀利容易得罪人。适合做律师、评论家、谈判专家。为人精明但人缘需注意维护。学会在适当的时候保持沉默是重要功课。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00768": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨机在官禄者事业上以口为业，善于辩论和谈判。适合法律、新闻、公关等行业。但职场中需注意避免因言惹祸，说话留三分。口才可以成就事业也可能毁掉事业。",
    "content": "巨机在官禄者事业上以口为业，善于辩论和谈判。适合法律、新闻、公关等行业。但职场中需注意避免因言惹祸，说话留三分。口才可以成就事业也可能毁掉事业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00769": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨机在夫妻者婚姻中口角争执多。夫妻双方都善于言辞，吵起来旗鼓相当。需学习少说多听，否则容易因话伤感情。把争辩的能量转化为交流的智慧。",
    "content": "巨机在夫妻者婚姻中口角争执多。夫妻双方都善于言辞，吵起来旗鼓相当。需学习少说多听，否则容易因话伤感情。把争辩的能量转化为交流的智慧。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00770": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机梁同宫为「机梁善谈格」。天机之智与天梁之慈结合，既是智谋又是善士。此组合之人有军师之才，善谈兵机，解厄救困。适合做顾问、医生、策士等既能用脑又能助人的职业。",
    "content": "机梁同宫为「机梁善谈格」。天机之智与天梁之慈结合，既是智谋又是善士。此组合之人有军师之才，善谈兵机，解厄救困。适合做顾问、医生、策士等既能用脑又能助人的职业。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00771": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机梁入命者智谋过人且有长者之风，喜欢帮助他人。适合做军师、顾问、医疗工作者。性格中有「老大」的气质，好管闲事但确实能解决问题。需要警惕变成爱管闲事的老好人。",
    "content": "机梁入命者智谋过人且有长者之风，喜欢帮助他人。适合做军师、顾问、医疗工作者。性格中有「老大」的气质，好管闲事但确实能解决问题。需要警惕变成爱管闲事的老好人。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00772": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机梁在财帛者财运来自智慧和助人。适合做教育培训、医疗保健、咨询服务等既能赚钱又能帮助他人的行业。不以利为先，反而财运不错。助人者天助之。",
    "content": "机梁在财帛者财运来自智慧和助人。适合做教育培训、医疗保健、咨询服务等既能赚钱又能帮助他人的行业。不以利为先，反而财运不错。助人者天助之。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00773": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机梁在官禄者事业上以智谋和助人为方向。适合做顾问、医生、教师、研究员等需要智慧和善心的职业。事业不求权但得人敬重，口碑是最好的名片。",
    "content": "机梁在官禄者事业上以智谋和助人为方向。适合做顾问、医生、教师、研究员等需要智慧和善心的职业。事业不求权但得人敬重，口碑是最好的名片。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00774": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "机梁在夫妻者配偶是自己的智囊和后盾。夫妻关系如师徒，互相扶持成长。婚姻稳定但需注意一方的唠叨和管束。互相欣赏对方的长处是婚姻稳固的基础。",
    "content": "机梁在夫妻者配偶是自己的智囊和后盾。夫妻关系如师徒，互相扶持成长。婚姻稳定但需注意一方的唠叨和管束。互相欣赏对方的长处是婚姻稳固的基础。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00775": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "日月同宫（或对拱）为「日月并明」或「日月反背」格的基础。太阳之阳刚与太阴之阴柔结合，阴阳调和。日生人光明磊落，夜生人则偏于内敛。日月并明者事业辉煌，日月反背者一...",
    "content": "日月同宫（或对拱）为「日月并明」或「日月反背」格的基础。太阳之阳刚与太阴之阴柔结合，阴阳调和。日生人光明磊落，夜生人则偏于内敛。日月并明者事业辉煌，日月反背者一生辛苦。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00776": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "日月在财帛者财路光明正大且稳定持久。适合正当行业，以信誉和服务赚钱。白天晚上各管一方的财运，钱财来源多元。稳定中求发展是最佳策略。",
    "content": "日月在财帛者财路光明正大且稳定持久。适合正当行业，以信誉和服务赚钱。白天晚上各管一方的财运，钱财来源多元。稳定中求发展是最佳策略。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00777": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "日月在官禄者事业全面，既有开拓力又有守成力。适合政府、大型企业的综合管理岗位。日月并明者事业如日中天，日月反背者则早出晚归白忙活。选择正确的时间点发力很重要。",
    "content": "日月在官禄者事业全面，既有开拓力又有守成力。适合政府、大型企业的综合管理岗位。日月并明者事业如日中天，日月反背者则早出晚归白忙活。选择正确的时间点发力很重要。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00778": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "日月在夫妻者配偶刚柔并济，是理想的人生伴侣。但日月同宫也可能暗示夫妻各自忙碌，聚少离多。需注意家庭与事业的平衡，给彼此留出相处的时间。",
    "content": "日月在夫妻者配偶刚柔并济，是理想的人生伴侣。但日月同宫也可能暗示夫妻各自忙碌，聚少离多。需注意家庭与事业的平衡，给彼此留出相处的时间。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00779": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨日同宫为化解暗昧之格。太阳之光化解巨门之暗，如阳光驱散阴霾。此组合之人用口才走正道，以光明正大的方式表达自己。口才是修来的福报而非祸根。",
    "content": "巨日同宫为化解暗昧之格。太阳之光化解巨门之暗，如阳光驱散阴霾。此组合之人用口才走正道，以光明正大的方式表达自己。口才是修来的福报而非祸根。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00780": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨日入命者口才佳但走正道，善于以光明的方式表达自己。适合做演讲、教育、电视主持等需要面向公众的口才工作。为人正直敢言，但有时过于直率。需注意方式方法。",
    "content": "巨日入命者口才佳但走正道，善于以光明的方式表达自己。适合做演讲、教育、电视主持等需要面向公众的口才工作。为人正直敢言，但有时过于直率。需注意方式方法。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00781": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨日在财帛者以名气、口才和信息赚钱，但走正路。适合做公众人物、培训师、知识付费等。财运靠的是公开的信息传播而非暗箱操作。正直是最好的商业策略。",
    "content": "巨日在财帛者以名气、口才和信息赚钱，但走正路。适合做公众人物、培训师、知识付费等。财运靠的是公开的信息传播而非暗箱操作。正直是最好的商业策略。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00782": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨日在官禄者事业上因口才和正直而受重用。适合从事教育、传媒、公益等公开性的行业。事业上有机会成为舆论领袖或公众人物。以德服人是事业长青的秘诀。",
    "content": "巨日在官禄者事业上因口才和正直而受重用。适合从事教育、传媒、公益等公开性的行业。事业上有机会成为舆论领袖或公众人物。以德服人是事业长青的秘诀。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00783": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "巨日在夫妻者婚姻中沟通良好，一方能以光明化解另一方的阴暗面。夫妻间愿意公开交流，关系透明。但太阳刺眼也可能让配偶感到压力，需要适度的空间。",
    "content": "巨日在夫妻者婚姻中沟通良好，一方能以光明化解另一方的阴暗面。夫妻间愿意公开交流，关系透明。但太阳刺眼也可能让配偶感到压力，需要适度的空间。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00784": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "阳梁同宫为「阳梁昌禄格」的基础（需加文昌化禄）。太阳之光明与天梁之福寿结合，如阳光普照下的老寿星。此组合之人有长者风范，考试运好，是最利于功名的组合之一。",
    "content": "阳梁同宫为「阳梁昌禄格」的基础（需加文昌化禄）。太阳之光明与天梁之福寿结合，如阳光普照下的老寿星。此组合之人有长者风范，考试运好，是最利于功名的组合之一。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00785": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "阳梁入命者心地光明、乐于助人，有长者之风。加文昌化禄则成阳梁昌禄格，考试夺魁之命。适合从政、教育、医疗等需要声誉和学识的行业。天生有师长气质。",
    "content": "阳梁入命者心地光明、乐于助人，有长者之风。加文昌化禄则成阳梁昌禄格，考试夺魁之命。适合从政、教育、医疗等需要声誉和学识的行业。天生有师长气质。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00786": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "阳梁在财帛者财运来自服务大众和长期积累。适合做公务员、教师、医生等稳定且有社会地位的职业。不求快钱，但财富稳中有升。服务越多回报越大。",
    "content": "阳梁在财帛者财运来自服务大众和长期积累。适合做公务员、教师、医生等稳定且有社会地位的职业。不求快钱，但财富稳中有升。服务越多回报越大。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00787": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "阳梁在官禄为最佳配置之一。事业上有名望、有福寿，适合从事教育、政府、医疗等公共事业。有「学而优则仕」的发展路径，考试运和晋升运好。功名是水到渠成的结果。",
    "content": "阳梁在官禄为最佳配置之一。事业上有名望、有福寿，适合从事教育、政府、医疗等公共事业。有「学而优则仕」的发展路径，考试运和晋升运好。功名是水到渠成的结果。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00788": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "阳梁在夫妻者配偶是自己的贵人和导师。配偶可能年长或在事业上帮助自己。婚姻如师生关系，互相敬重。夫妻间注重精神层面的契合，但需当心一方过于说教。",
    "content": "阳梁在夫妻者配偶是自己的贵人和导师。配偶可能年长或在事业上帮助自己。婚姻如师生关系，互相敬重。夫妻间注重精神层面的契合，但需当心一方过于说教。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00789": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "武府同宫为财库充实之格。武曲之财与天府之库结合，如金钱存入保险库。此组合之人赚钱能力强且善于守财，是紫微斗数中最富有的组合之一。财运稳健持久，是真正的财富积累者...",
    "content": "武府同宫为财库充实之格。武曲之财与天府之库结合，如金钱存入保险库。此组合之人赚钱能力强且善于守财，是紫微斗数中最富有的组合之一。财运稳健持久，是真正的财富积累者。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00790": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "武府在财帛为最顶级配置。主正财运极强且善于积累，财库充盈。适合金融、房地产、制造业等需要资金运作的行业。赚钱和守财能力双强，一生富足。财富如滚雪球越滚越大。",
    "content": "武府在财帛为最顶级配置。主正财运极强且善于积累，财库充盈。适合金融、房地产、制造业等需要资金运作的行业。赚钱和守财能力双强，一生富足。财富如滚雪球越滚越大。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00791": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "武府在官禄者事业稳健上升，适合做金融高管、企业老板、政府财政官员等。事业上善于资源管理和资金运作，能在大型组织中获得重要职位。稳中求胜是事业的底色。",
    "content": "武府在官禄者事业稳健上升，适合做金融高管、企业老板、政府财政官员等。事业上善于资源管理和资金运作，能在大型组织中获得重要职位。稳中求胜是事业的底色。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00792": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "武府在夫妻者配偶理财能力强，是家庭的经济支柱或管家。婚姻以经济稳定为基础，夫妻共同经营家庭的财富。但过于务实可能缺乏浪漫，需在物质之外培养情感。",
    "content": "武府在夫妻者配偶理财能力强，是家庭的经济支柱或管家。婚姻以经济稳定为基础，夫妻共同经营家庭的财富。但过于务实可能缺乏浪漫，需在物质之外培养情感。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  },
  "KB-ziwei-00793": {
    "tags": [],
    "confidence": 0.5,
    "category": "R6-深度精修",
    "difficulty": "intermediate",
    "access_level": "registered",
    "summary": "武贪同宫为「武贪不发少年人」格。武曲之正财与贪狼之偏财结合，如正财碰上了投机高手。此组合之人早年财运波折，中年以后才开始发达。晚发的命格，但发财后势头强劲。",
    "content": "武贪同宫为「武贪不发少年人」格。武曲之正财与贪狼之偏财结合，如正财碰上了投机高手。此组合之人早年财运波折，中年以后才开始发达。晚发的命格，但发财后势头强劲。",
    "source_ids": [
      "SRC-LEGACY-001"
    ]
  }
},

  inverted_index: {},

  categories: {
  "R6-深度精修": [
    "KB-ziwei-00700",
    "KB-ziwei-00701",
    "KB-ziwei-00702",
    "KB-ziwei-00703",
    "KB-ziwei-00704",
    "KB-ziwei-00705",
    "KB-ziwei-00706",
    "KB-ziwei-00707",
    "KB-ziwei-00708",
    "KB-ziwei-00709",
    "KB-ziwei-00710",
    "KB-ziwei-00711",
    "KB-ziwei-00712",
    "KB-ziwei-00713",
    "KB-ziwei-00714",
    "KB-ziwei-00715",
    "KB-ziwei-00716",
    "KB-ziwei-00717",
    "KB-ziwei-00718",
    "KB-ziwei-00719",
    "KB-ziwei-00720",
    "KB-ziwei-00721",
    "KB-ziwei-00722",
    "KB-ziwei-00723",
    "KB-ziwei-00724",
    "KB-ziwei-00725",
    "KB-ziwei-00726",
    "KB-ziwei-00727",
    "KB-ziwei-00728",
    "KB-ziwei-00729",
    "KB-ziwei-00730",
    "KB-ziwei-00731",
    "KB-ziwei-00732",
    "KB-ziwei-00733",
    "KB-ziwei-00734",
    "KB-ziwei-00735",
    "KB-ziwei-00736",
    "KB-ziwei-00737",
    "KB-ziwei-00738",
    "KB-ziwei-00739",
    "KB-ziwei-00740",
    "KB-ziwei-00741",
    "KB-ziwei-00742",
    "KB-ziwei-00743",
    "KB-ziwei-00744",
    "KB-ziwei-00745",
    "KB-ziwei-00746",
    "KB-ziwei-00747",
    "KB-ziwei-00748",
    "KB-ziwei-00749",
    "KB-ziwei-00750",
    "KB-ziwei-00751",
    "KB-ziwei-00752",
    "KB-ziwei-00753",
    "KB-ziwei-00754",
    "KB-ziwei-00755",
    "KB-ziwei-00756",
    "KB-ziwei-00757",
    "KB-ziwei-00758",
    "KB-ziwei-00759",
    "KB-ziwei-00760",
    "KB-ziwei-00761",
    "KB-ziwei-00762",
    "KB-ziwei-00763",
    "KB-ziwei-00764",
    "KB-ziwei-00765",
    "KB-ziwei-00766",
    "KB-ziwei-00767",
    "KB-ziwei-00768",
    "KB-ziwei-00769",
    "KB-ziwei-00770",
    "KB-ziwei-00771",
    "KB-ziwei-00772",
    "KB-ziwei-00773",
    "KB-ziwei-00774",
    "KB-ziwei-00775",
    "KB-ziwei-00776",
    "KB-ziwei-00777",
    "KB-ziwei-00778",
    "KB-ziwei-00779",
    "KB-ziwei-00780",
    "KB-ziwei-00781",
    "KB-ziwei-00782",
    "KB-ziwei-00783",
    "KB-ziwei-00784",
    "KB-ziwei-00785",
    "KB-ziwei-00786",
    "KB-ziwei-00787",
    "KB-ziwei-00788",
    "KB-ziwei-00789",
    "KB-ziwei-00790",
    "KB-ziwei-00791",
    "KB-ziwei-00792",
    "KB-ziwei-00793"
  ]
},

  /**
   * 按关键词搜索（标签匹配）
   */
  search(query) {
    if (!query) return [];
    const words = query.split(/[\s,，、]+/).filter(w => w.length > 0);
    const scored = {};
    for (const word of words) {
      for (const [tag, ids] of Object.entries(this.inverted_index)) {
        if (tag.includes(word) || word.includes(tag)) {
          for (const id of ids) {
            scored[id] = (scored[id] || 0) + 1;
          }
        }
      }
    }
    return Object.entries(scored)
      .sort((a, b) => b[1] - a[1])
      .map(([id, score]) => ({ entry_id: id, score, ...this.entries[id] }))
      .filter(e => e.content);
  },

  /**
   * 按分类获取
   */
  byCategory(cat) {
    const ids = this.categories[cat] || [];
    return ids.map(id => ({ entry_id: id, ...this.entries[id] })).filter(e => e.content);
  },

  /**
   * 按标签获取
   */
  byTag(tag) {
    const ids = this.inverted_index[tag] || [];
    return ids.map(id => ({ entry_id: id, ...this.entries[id] })).filter(e => e.content);
  },

  /**
   * 追溯来源
   */
  traceSource(entry_id) {
    const e = this.entries[entry_id];
    if (!e || !e.source_ids) return [];
    return e.source_ids;
  },

  /**
   * 统计
   */
  stats() {
    return {
      module: this.module,
      version: this.version,
      entry_count: Object.keys(this.entries).length,
      tag_count: Object.keys(this.inverted_index).length,
      category_count: Object.keys(this.categories).length,
    };
  }
};

// 挂到全局
try { window.ZIWEI_MODEL = ZIWEI_MODEL; } catch(e) {}
try { module.exports = ZIWEI_MODEL; } catch(e) {}
