/**
 * 易道智鉴 · 开运商城数据
 * 生成时间：2026-06-15
 */

window.SHOP_DATA = {
  // 分类数据
  categories: [
    {
      id: 'mingli-huajie',
      name: '命理化解吉祥物',
      icon: '🔮',
      description: '根据五行喜用，选择相应吉祥物补缺平衡',
      subcategories: [
        { id: 'jin', name: '五行缺金', color: '#95a5a6', desc: '补金增强决断力、财运' },
        { id: 'mu', name: '五行缺木', color: '#27ae60', desc: '补木增强生机、仁德' },
        { id: 'shui', name: '五行缺水', color: '#2980b9', desc: '补水增强智慧、财运' },
        { id: 'huo', name: '五行缺火', color: '#e74c3c', desc: '补火增强礼仪、活力' },
        { id: 'tu', name: '五行缺土', color: '#e67e22', desc: '补土增强信德、稳定' }
      ]
    },
    {
      id: 'rujia',
      name: '儒家吉祥物',
      icon: '📚',
      description: '学而时习之，不亦说乎——助力学业、修身、立德',
      subcategories: [
        { id: 'study', name: '学业助运', color: '#3498db', desc: '提升学习效率、考试成绩' },
        { id: 'virtue', name: '修德养性', color: '#9b59b6', desc: '培养君子品格、涵养' }
      ]
    },
    {
      id: 'fojia',
      name: '佛家吉祥物',
      icon: '🙏',
      description: '诸恶莫作，众善奉行——祈福、消业、增慧',
      subcategories: [
        { id: 'blessing', name: '祈福消业', color: '#f39c12', desc: '消灾祈福、平安吉祥' },
        { id: 'wisdom', name: '开慧增智', color: '#1abc9c', desc: '增长智慧、明心见性' }
      ]
    },
    {
      id: 'daojia',
      name: '道家吉祥物',
      icon: '☯️',
      description: '道法自然，天人合一——辟邪、镇宅、养生',
      subcategories: [
        { id: 'protect', name: '辟邪镇宅', color: '#c0392b', desc: '驱邪避凶、家宅平安' },
        { id: 'health', name: '养生延年', color: '#16a085', desc: '延年益寿、身心康泰' }
      ]
    },
    {
      id: 'yifang',
      name: '名医名方',
      icon: '💊',
      description: '上医治未病，中医治欲病，下医治已病——中医养生智慧',
      subcategories: [
        { id: 'wanji', name: '经典丸剂', color: '#e67e22', desc: '古法炮制，功效确切' },
        { id: 'gaofang', name: '经典膏方', color: '#8e44ad', desc: '滋补调理，四季皆宜' },
        { id: 'mingyi', name: '名医推荐', color: '#3498db', desc: '历代名医经典方剂' },
        { id: 'daoyi', name: '道医专区', color: '#16a085', desc: '道医传承人 · 丹道养生 · 符箓祝由' },
        { id: 'foyi', name: '佛医专区', color: '#e74c3c', desc: '佛医传承人 · 禅修疗愈 · 药师法门' }
      ]
    },
    {
      id: 'jingdian',
      name: '儒道释经典著作',
      icon: '📜',
      description: '儒道释三教经典注疏本·白话本，修身明德、悟道修真、明心见性',
      subcategories: [
        { id: 'rujia-jing', name: '儒家经典', color: '#c0392b', desc: '修齐治平·立德立言' },
        { id: 'daojia-jing', name: '道家经典', color: '#16a085', desc: '道法自然·养生修真' },
        { id: 'fojia-jing', name: '佛家经典', color: '#8e44ad', desc: '明心见性·般若智慧' }
      ]
    },
    {
      id: 'zibuyangsheng',
      name: '滋补养生',
      icon: '🧉',
      description: '精选道地名贵滋补品，药食同源，以养防病，延年益寿',
      subcategories: [
        { id: 'renshen-lei', name: '参茸贵细', color: '#c0392b', desc: '人参鹿茸等名贵滋补品' },
        { id: 'lingzhi-lei', name: '灵芝孢子', color: '#8e44ad', desc: '灵芝孢子粉破壁精华' },
        { id: 'chongcao-lei', name: '虫草燕窝', color: '#f39c12', desc: '冬虫夏草及燕窝系列' },
        { id: 'ejiao-lei', name: '阿胶膏方', color: '#e74c3c', desc: '阿胶及滋补膏方系列' },
        { id: 'yaoshan-lei', name: '药膳食材', color: '#27ae60', desc: '药食同源煲汤炖品' }
      ]
    },
    {
      id: 'chayin',
      name: '名茶雅韵',
      icon: '🍵',
      description: '中国十大名茶及地方名优茶品，品茗悟道，茶禅一味',
      subcategories: [
        { id: 'lvcha', name: '绿茶', color: '#27ae60', desc: '龙井/碧螺春/信阳毛尖' },
        { id: 'wulong', name: '乌龙茶', color: '#e67e22', desc: '铁观音/大红袍/冻顶' },
        { id: 'puer', name: '黑茶·普洱', color: '#795548', desc: '陈年普洱及黑茶系列' },
        { id: 'baicha', name: '白茶·黄茶', color: '#f39c12', desc: '白毫银针/君山银针' },
        { id: 'huacha', name: '花茶·养生茶', color: '#e91e63', desc: '茉莉花茶/养生花草茶' }
      ]
    },
    {
      id: 'ganguo',
      name: '干果零食',
      icon: '🥜',
      description: '健康坚果·养生干果·地方特产零食，天然无添加',
      subcategories: [
        { id: 'jiankang-hetao', name: '坚果炒货', color: '#e67e22', desc: '核桃/杏仁/腰果/松子' },
        { id: 'yangwei-ganhuo', name: '养生干货', color: '#c0392b', desc: '红枣/枸杞/桂圆/莲子' },
        { id: 'lvse-ganguo', name: '绿色特产', color: '#27ae60', desc: '葡萄干/无花果/柿饼' },
        { id: 'lingzhi-guo', name: '零嘴果脯', color: '#f39c12', desc: '山楂/陈皮/梅子系列' }
      ]
    },
    {
      id: 'school',
      name: '按派别',
      icon: '☯️',
      description: '按佛道儒法器养生茶饮等派别筛选',
      subcategories: [
        { id: 'buddhist', name: '佛教', color: '#f39c12', desc: '佛教名山道场法器圣物' },
        { id: 'daoist', name: '道教', color: '#27ae60', desc: '道教名山法器养生丹道' },
        { id: 'confucian', name: '儒家', color: '#3498db', desc: '儒家经典文房修身养德' },
        { id: 'instrument', name: '法器', color: '#9b59b6', desc: '修行法器颂钵木鱼磬铃' },
        { id: 'health', name: '养生', color: '#e67e22', desc: '滋补养生名医名方膏方' },
        { id: 'tea', name: '茶饮', color: '#1abc9c', desc: '名茶雅韵花茶养生茶' }
      ]
    },
    {
      id: 'gongyipin',
      name: '工艺珍品',
      icon: '🏺',
      description: '中国传统工艺品，承载千年文化，匠心独运，赏用兼宜',
      subcategories: [
        { id: 'yuqi', name: '玉器珍玩', color: '#16a085', desc: '和田玉/翡翠/岫玉雕刻' },
        { id: 'taoci', name: '陶瓷名器', color: '#2980b9', desc: '景德镇/宜兴紫砂/汝窑' },
        { id: 'sichou', name: '丝绸刺绣', color: '#c0392b', desc: '苏绣/湘绣/蜀绣/云锦' },
        { id: 'wenfang', name: '文房四宝', color: '#2c3e50', desc: '笔墨纸砚/文房雅玩' },
        { id: 'baiwu', name: '摆件饰品', color: '#8e44ad', desc: '木雕/铜器/漆器工艺品' }
      ]
    }
  ],

  // 产品数据
  products: [
    // ===== 命理化解吉祥物 =====
    // 五行缺金
    {
      id: 'jin-001',
      categoryId: 'mingli-huajie',
      subcategoryId: 'jin',
      name: '纯铜招财貔貅',
      image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop',
      price: '结缘 168-588',
      rating: 4.8,
      sales: 2356,
      description: '铜制貔貅，招财进宝，补金旺运',
      effects: '增强决断力、招财聚财、化解煞气',
      suitable: '八字缺金、财运不佳、决策犹豫者',
      material: '纯铜精铸',
      size: '高度8-15cm可选',
      origin: '浙江杭州',
      tags: ['招财', '补金', '镇宅'],
      reason: '貔貅为招财瑞兽，铜属金，两者结合，补金招财效果显著。适合八字缺金、求财心切者供奉。'
    },
    {
      id: 'jin-002',
      categoryId: 'mingli-huajie',
      subcategoryId: 'jin',
      name: '手工铜风铃',
      image: 'https://images.unsplash.com/photo-1517925037513-40c7a1f4e5ad?w=400&h=400&fit=crop',
      price: '结缘 88-268',
      rating: 4.7,
      sales: 1823,
      description: '清脆悠扬，金声振气，化解阴煞',
      effects: '净化气场、驱除阴气、补金生水',
      suitable: '八字缺金、住宅阴暗、气场沉闷者',
      material: '黄铜/青铜',
      size: '总长40-60cm',
      origin: '福建泉州',
      tags: ['化煞', '补金', '风水'],
      reason: '铜铃声清脆，五行属金，挂于门廊窗边，可振阳祛阴，补金调气。'
    },
    {
      id: 'jin-003',
      categoryId: 'mingli-huajie',
      subcategoryId: 'jin',
      name: '白水晶摆件',
      image: 'https://images.unsplash.com/photo-1536591384383-e52f0effd8d7?w=400&h=400&fit=crop',
      price: '结缘 128-888',
      rating: 4.9, premium: true,
      sales: 3245,
      description: '晶莹剔透，金白相应，净化磁场',
      effects: '净化心灵、提升记忆、补金生水',
      suitable: '八字缺金、精神压力大、需要专注者',
      material: '天然白水晶',
      size: '高度5-20cm可选',
      origin: '江苏东海',
      tags: ['净化', '补金', '智慧'],
      reason: '白水晶为水晶之王，能量纯净，对应金行，可净化磁场、安定心神。'
    },
    // 五行缺木
    {
      id: 'mu-001',
      categoryId: 'mingli-huajie',
      subcategoryId: 'mu',
      name: '绿幽灵水晶球',
      image: 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=400&h=400&fit=crop',
      price: '结缘 288-1688',
      rating: 4.9, premium: true,
      sales: 1567,
      description: '绿意盎然，生机勃勃，招正财',
      effects: '招正财、增强生机、提升事业',
      suitable: '八字缺木、事业发展受阻、缺乏活力者',
      material: '天然绿幽灵水晶',
      size: '直径4-8cm',
      origin: '巴西进口',
      tags: ['正财', '补木', '事业'],
      reason: '绿幽灵为招正财水晶，绿色对应木行，适合上班族、创业者摆放办公桌，助事业发展。'
    },
    {
      id: 'mu-002',
      categoryId: 'mingli-huajie',
      subcategoryId: 'mu',
      name: '小叶紫檀手串',
      image: 'https://images.unsplash.com/photo-1604005645543-859acc0770a8?w=400&h=400&fit=crop',
      price: '结缘 188-3688',
      rating: 4.8,
      sales: 4521,
      description: '檀香袅袅，木德养仁，安神定志',
      effects: '安神助眠、培养仁德、补木生火',
      suitable: '八字缺木、睡眠不佳、心神不宁者',
      material: '印度小叶紫檀',
      size: '珠径1.5-2.0cm',
      origin: '印度进口',
      tags: ['安神', '补木', '养生'],
      reason: '小叶紫檀为木中极品，佩戴可补木德，安神养心，长期佩戴有益身心。'
    },
    {
      id: 'mu-003',
      categoryId: 'mingli-huajie',
      subcategoryId: 'mu',
      name: '发财树盆栽',
      image: 'https://images.unsplash.com/photo-1463320898484-cdee8141c787?w=400&h=400&fit=crop',
      price: '结缘 68-288',
      rating: 4.7,
      sales: 8932,
      description: '枝繁叶茂，财源广进，生机盎然',
      effects: '招财进宝、净化空气、补木旺运',
      suitable: '八字缺木、办公居家、求财者',
      material: '天然植物',
      size: '高度30-120cm',
      origin: '广东广州',
      tags: ['招财', '补木', '生机'],
      reason: '发财树寓意吉祥，绿叶属木，摆放室内可补木气、生财气，一举两得。'
    },
    // 五行缺水
    {
      id: 'shui-001',
      categoryId: 'mingli-huajie',
      subcategoryId: 'shui',
      name: '黑曜石貔貅',
      image: 'https://images.unsplash.com/photo-1577177430157-b95b13e7cb0e?w=400&h=400&fit=crop',
      price: '结缘 168-688',
      rating: 4.8,
      sales: 3256,
      description: '深沉如夜，水德润下，辟邪招财',
      effects: '辟邪化煞、招财聚财、补水增智',
      suitable: '八字缺水、容易招惹邪祟、财运不佳者',
      material: '天然黑曜石',
      size: '高度6-12cm',
      origin: '墨西哥进口',
      tags: ['辟邪', '补水', '招财'],
      reason: '黑曜石为天然火山琉璃，色黑属水，可辟邪化煞，同时补水旺智。'
    },
    {
      id: 'shui-002',
      categoryId: 'mingli-huajie',
      subcategoryId: 'shui',
      name: '海蓝宝吊坠',
      image: 'https://images.unsplash.com/photo-1624630174352-e0b45b435390?w=400&h=400&fit=crop',
      price: '结缘 388-2688',
      rating: 4.9, premium: true,
      sales: 1892,
      description: '蔚蓝如海，水之精华，智慧之石',
      effects: '增强智慧、改善沟通、补水润燥',
      suitable: '八字缺水、表达能力弱、需要灵感者',
      material: '天然海蓝宝',
      size: '珠径0.8-1.5cm',
      origin: '巴西进口',
      tags: ['智慧', '补水', '沟通'],
      reason: '海蓝宝为水属性宝石，对应喉轮，可增强表达能力、提升智慧，适合缺水者佩戴。'
    },
    {
      id: 'shui-003',
      categoryId: 'mingli-huajie',
      subcategoryId: 'shui',
      name: '风水鱼缸摆件',
      image: 'https://images.unsplash.com/photo-1522069163288-9a2761fa8d0e?w=400&h=400&fit=crop',
      price: '结缘 288-1888',
      rating: 4.6,
      sales: 2345,
      description: '鱼跃龙门，活水生财，灵动吉祥',
      effects: '招财旺运、活跃气场、补水生木',
      suitable: '八字缺水、财运停滞、需要生气者',
      material: '玻璃/亚克力',
      size: '长度40-120cm',
      origin: '广东佛山',
      tags: ['招财', '补水', '风水'],
      reason: '水为财源，鱼缸可养水生财，活鱼游动更添生气，为缺水者首选补运之物。'
    },
    // 五行缺火
    {
      id: 'huo-001',
      categoryId: 'mingli-huajie',
      subcategoryId: 'huo',
      name: '南红玛瑙手串',
      image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop',
      price: '结缘 288-3688',
      rating: 4.9, premium: true,
      sales: 4567,
      description: '赤红如火，热情洋溢，活力之石',
      effects: '增强活力、提升人缘、补火暖身',
      suitable: '八字缺火、体质虚寒、人际关系淡者',
      material: '天然南红玛瑙',
      size: '珠径1.0-1.8cm',
      origin: '四川凉山',
      tags: ['活力', '补火', '人缘'],
      reason: '南红玛瑙色红属火，佩戴可增强阳气、改善人缘，为补火首选宝石。'
    },
    {
      id: 'huo-002',
      categoryId: 'mingli-huajie',
      subcategoryId: 'huo',
      name: '紫水晶洞',
      image: 'https://images.unsplash.com/photo-1605106702842-01a887a31122?w=400&h=400&fit=crop',
      price: '结缘 588-5888',
      rating: 4.8,
      sales: 1234,
      description: '紫气东来，高贵典雅，智慧之洞',
      effects: '镇宅辟邪、增强智慧、补火生土',
      suitable: '八字缺火、需要智慧、镇宅需求者',
      material: '天然紫水晶',
      size: '重量1-10kg',
      origin: '乌拉圭进口',
      tags: ['智慧', '补火', '镇宅'],
      reason: '紫水晶为智慧之石，紫色属火，可镇宅辟邪、开发智慧，适合摆放书房。'
    },
    {
      id: 'huo-003',
      categoryId: 'mingli-huajie',
      subcategoryId: 'huo',
      name: '香薰蜡烛套装',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
      price: '结缘 88-388',
      rating: 4.7,
      sales: 6789,
      description: '烛光摇曳，馨香满室，温馨吉祥',
      effects: '营造氛围、提升情绪、补火暖房',
      suitable: '八字缺火、居家布置、气氛营造者',
      material: '大豆蜡/天然精油',
      size: '容量100-300g',
      origin: '浙江杭州',
      tags: ['温馨', '补火', '氛围'],
      reason: '蜡烛为火之象，点燃可补火气，配合香薰更能调节情绪、营造温馨氛围。'
    },
    // 五行缺土
    {
      id: 'tu-001',
      categoryId: 'mingli-huajie',
      subcategoryId: 'tu',
      name: '黄玉招财摆件',
      image: 'https://images.unsplash.com/photo-1615485290382-441e4d5c7ef5?w=400&h=400&fit=crop',
      price: '结缘 288-1688',
      rating: 4.8,
      sales: 2345,
      description: '金黄温润，土德厚载，财运亨通',
      effects: '招财聚财、稳定运势、补土生金',
      suitable: '八字缺土、财运不稳、事业波动者',
      material: '天然黄玉',
      size: '高度8-20cm',
      origin: '新疆和田',
      tags: ['招财', '补土', '稳定'],
      reason: '黄玉色黄属土，为招财之石，可补土生金，稳固财运根基。'
    },
    {
      id: 'tu-002',
      categoryId: 'mingli-huajie',
      subcategoryId: 'tu',
      name: '陶瓷招财猫',
      image: 'https://images.unsplash.com/photo-1573867639040-6dd25fa3b611?w=400&h=400&fit=crop',
      price: '结缘 68-288',
      rating: 4.6,
      sales: 12345,
      description: '憨态可掬，招财纳福，日本传统',
      effects: '招财迎客、增加人气、补土生金',
      suitable: '八字缺土、开店经商、需要客源者',
      material: '陶瓷',
      size: '高度15-30cm',
      origin: '江西景德镇',
      tags: ['招财', '补土', '迎客'],
      reason: '招财猫为经典招财吉祥物，陶瓷属土，摆放店铺可招财迎客、补土旺运。'
    },
    {
      id: 'tu-003',
      categoryId: 'mingli-huajie',
      subcategoryId: 'tu',
      name: '方形陶瓷花瓶',
      image: 'https://images.unsplash.com/photo-1616708514390-3332c3e45438?w=400&h=400&fit=crop',
      price: '结缘 168-688',
      rating: 4.7,
      sales: 3456,
      description: '方正规整，土德稳重，养花纳气',
      effects: '调和气场、承载生机、补土平运',
      suitable: '八字缺土、居家装饰、需要稳定者',
      material: '陶瓷',
      size: '高度20-50cm',
      origin: '江西景德镇',
      tags: ['装饰', '补土', '稳定'],
      reason: '方形象土，陶瓷亦属土，插花摆放可调和气场、补土旺运，一举两得。'
    },

    // ===== 儒家吉祥物 =====
    {
      id: 'rujia-001',
      categoryId: 'rujia',
      subcategoryId: 'study',
      name: '文昌塔（七层/九层）',
      image: 'https://images.unsplash.com/photo-1508808787069-421eaa3eb10a?w=400&h=400&fit=crop',
      price: '结缘 168-888',
      rating: 4.9, premium: true,
      sales: 5678,
      description: '层层递进，文运昌隆，学业有成',
      effects: '提升学业、增强记忆、考试顺利',
      suitable: '学生、考生、学术研究者',
      material: '铜/水晶/陶瓷可选',
      size: '高度15-35cm',
      origin: '江苏苏州',
      tags: ['学业', '考试', '智慧'],
      reason: '文昌塔为助学风水法器，摆放书桌可增强文运、助力考试，学生必备。'
    },
    {
      id: 'rujia-002',
      categoryId: 'rujia',
      subcategoryId: 'study',
      name: '竹子摆件（节节高）',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop',
      price: '结缘 88-388',
      rating: 4.8,
      sales: 4567,
      description: '虚心有节，步步高升，君子之风',
      effects: '事业晋升、学业进步、品德修养',
      suitable: '职场人士、学生、追求进步者',
      material: '竹制/仿玉/铜制',
      size: '高度20-40cm',
      origin: '浙江安吉',
      tags: ['晋升', '学业', '君子'],
      reason: '竹有君子之风，寓意节节高升，摆放办公桌或书房可助事业学业双丰收。'
    },
    {
      id: 'rujia-003',
      categoryId: 'rujia',
      subcategoryId: 'virtue',
      name: '孔子像（精铜铸造）',
      image: 'https://images.unsplash.com/photo-1569865875921-42ffa409fa9e?w=400&h=400&fit=crop',
      price: '结缘 388-1888',
      rating: 4.9, premium: true,
      sales: 2345,
      description: '至圣先师，万世师表，德配天地',
      effects: '尊师重道、修身养德、学业有成',
      suitable: '教育工作者、学生家庭、文化场所',
      material: '精铜铸造',
      size: '高度20-40cm',
      origin: '山东曲阜',
      tags: ['师德', '文化', '修身'],
      reason: '孔子为万世师表，供奉孔子像可激励修身向学、传承儒家文化。'
    },
    {
      id: 'rujia-004',
      categoryId: 'rujia',
      subcategoryId: 'virtue',
      name: '论语竹简',
      image: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=400&h=400&fit=crop',
      price: '结缘 128-688',
      rating: 4.8,
      sales: 3456,
      description: '半部论语，治天下事，圣贤之言',
      effects: '修身养德、启迪智慧、传承经典',
      suitable: '文化爱好者、学生、教育者',
      material: '竹简/仿古工艺',
      size: '长度50-100cm',
      origin: '湖南长沙',
      tags: ['经典', '修身', '智慧'],
      reason: '《论语》为儒家经典，竹简装帧古雅，可收藏研读、传承圣贤智慧。'
    },
    {
      id: 'rujia-005',
      categoryId: 'rujia',
      subcategoryId: 'study',
      name: '毛笔架套装',
      image: 'https://images.unsplash.com/photo-1608924962640-adcadad6c22a?w=400&h=400&fit=crop',
      price: '结缘 188-888',
      rating: 4.7,
      sales: 2345,
      description: '文房四宝，翰墨飘香，雅致生活',
      effects: '培养情趣、提升修养、书法练习',
      suitable: '书法爱好者、学生、文化人士',
      material: '红木/陶瓷',
      size: '长度30-50cm',
      origin: '安徽宣城',
      tags: ['书法', '修养', '文房'],
      reason: '毛笔架为文房雅器，配套毛笔墨汁，可练习书法、陶冶情操。'
    },

    // ===== 佛家吉祥物 =====
    {
      id: 'fojia-001',
      categoryId: 'fojia',
      subcategoryId: 'blessing',
      name: '星月菩提佛珠（108颗）',
      image: 'https://images.unsplash.com/photo-1559312026-0fc83f3c0bb8?w=400&h=400&fit=crop',
      price: '结缘 168-1688',
      rating: 4.9, premium: true,
      sales: 8765,
      description: '星月菩提，佛珠之王，修行之伴',
      effects: '静心祈福、消除业障、增长福慧',
      suitable: '佛弟子、修行者、追求内心平静者',
      material: '星月菩提子',
      size: '珠径0.8-1.2cm',
      origin: '尼泊尔进口',
      tags: ['祈福', '修行', '静心'],
      reason: '星月菩提为佛珠上品，持诵可消除业障、增长福慧，为修行者必备法器。'
    },
    {
      id: 'fojia-002',
      categoryId: 'fojia',
      subcategoryId: 'blessing',
      name: '藏式转经筒',
      image: 'https://images.unsplash.com/photo-1517434200893-8b3f27c2ab4c?w=400&h=400&fit=crop',
      price: '结缘 88-688',
      rating: 4.8,
      sales: 4567,
      description: '转经筒转，功德无量，祈福众生',
      effects: '积累功德、祈福消业、心神安宁',
      suitable: '修行者、祈福者、信众',
      material: '铜/木质',
      size: '高度10-25cm',
      origin: '西藏拉萨',
      tags: ['祈福', '功德', '消业'],
      reason: '转经筒内藏六字真言，转动等同持诵，可积累功德、祈福消业。'
    },
    {
      id: 'fojia-003',
      categoryId: 'fojia',
      subcategoryId: 'wisdom',
      name: '翡翠佛像挂坠',
      image: 'https://images.unsplash.com/photo-1508184967-8af0debbcb1f?w=400&h=400&fit=crop',
      price: '结缘 388-8888',
      rating: 4.9, premium: true,
      sales: 2345,
      description: '翡翠玉佛，慈悲为怀，智慧圆满',
      effects: '护佑平安、增长智慧、消除灾难',
      suitable: '信众、求智慧者、出行者',
      material: '天然翡翠',
      size: '高度3-6cm',
      origin: '缅甸进口',
      tags: ['护佑', '智慧', '平安'],
      reason: '玉佛为护身圣物，佩戴可得佛力加持，护佑平安、增长智慧。'
    },
    {
      id: 'fojia-004',
      categoryId: 'fojia',
      subcategoryId: 'wisdom',
      name: '莲花生大士像',
      image: 'https://images.unsplash.com/photo-1469041796923-f1febd8a90be?w=400&h=400&fit=crop',
      price: '结缘 588-2888',
      rating: 4.8,
      sales: 1234,
      description: '莲师加持，消除障碍，智慧增长',
      effects: '消除障碍、增长智慧、护佑修行',
      suitable: '密宗修行者、求智慧者',
      material: '铜镀金/紫铜',
      size: '高度15-30cm',
      origin: '西藏拉萨',
      tags: ['智慧', '护佑', '密宗'],
      reason: '莲花生大士为密宗祖师，供奉莲师像可得加持、消除修行障碍。'
    },
    {
      id: 'fojia-005',
      categoryId: 'fojia',
      subcategoryId: 'blessing',
      name: '甘露丸佩戴盒',
      image: 'https://images.unsplash.com/photo-1600037052524-98bf01dcb4cc?w=400&h=400&fit=crop',
      price: '结缘 68-288',
      rating: 4.7,
      sales: 5678,
      description: '甘露加持，消灾延寿，护身之宝',
      effects: '消灾延寿、护身辟邪、增加福报',
      suitable: '信众、体弱多病者、出行者',
      material: '银/铜',
      size: '直径2-3cm',
      origin: '西藏拉萨',
      tags: ['消灾', '延寿', '护身'],
      reason: '甘露丸为藏传佛教圣物，佩戴可得加持护佑，消灾延寿。'
    },

    // ===== 道家吉祥物 =====
    {
      id: 'daojia-001',
      categoryId: 'daojia',
      subcategoryId: 'protect',
      name: '桃木剑（镇宅辟邪）',
      image: 'https://images.unsplash.com/photo-1584208636194-1407bb6f5b9e?w=400&h=400&fit=crop',
      price: '结缘 128-688',
      rating: 4.8,
      sales: 6789,
      description: '桃木纯阳，辟邪镇宅，斩妖除魔',
      effects: '辟邪化煞、镇宅护佑、驱除阴气',
      suitable: '住宅有邪气、经常做噩梦、需要护佑者',
      material: '天然桃木',
      size: '长度40-100cm',
      origin: '山东泰安',
      tags: ['辟邪', '镇宅', '护佑'],
      reason: '桃木为纯阳之木，自古为辟邪神器，挂于门后可镇宅护家、驱邪避凶。'
    },
    {
      id: 'daojia-002',
      categoryId: 'daojia',
      subcategoryId: 'protect',
      name: '太极八卦镜',
      image: 'https://images.unsplash.com/photo-1532935131075-21da6ed46c03?w=400&h=400&fit=crop',
      price: '结缘 68-388',
      rating: 4.7,
      sales: 8765,
      description: '太极流转，八卦护卫，化煞为祥',
      effects: '化解煞气、反射厄运、调和阴阳',
      suitable: '住宅有冲煞、需要化煞者',
      material: '铜/木质',
      size: '直径10-30cm',
      origin: '江西龙虎山',
      tags: ['化煞', '护佑', '风水'],
      reason: '八卦镜为风水化煞法器，可反射冲煞、调和阴阳，挂于门楣或窗边使用。'
    },
    {
      id: 'daojia-003',
      categoryId: 'daojia',
      subcategoryId: 'protect',
      name: '道家符箓护身符',
      image: 'https://images.unsplash.com/photo-1570034752296-36ca0c3e9e95?w=400&h=400&fit=crop',
      price: '结缘 38-188',
      rating: 4.8,
      sales: 12345,
      description: '朱砂黄纸，道法加持，护身辟邪',
      effects: '护身辟邪、出行平安、化解凶险',
      suitable: '出行者、体弱多病者、需要护佑者',
      material: '黄纸朱砂',
      size: '长度20-30cm',
      origin: '江西龙虎山',
      tags: ['护身', '辟邪', '平安'],
      reason: '道家符箓经法师加持，可护身辟邪，随身携带可得神力护佑。'
    },
    {
      id: 'daojia-004',
      categoryId: 'daojia',
      subcategoryId: 'health',
      name: '铜制药葫芦',
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop',
      price: '结缘 188-888',
      rating: 4.7,
      sales: 3456,
      description: '葫芦纳福，药王护佑，健康长寿',
      effects: '祛病消灾、收纳病气、延年益寿',
      suitable: '体弱多病者、老年人、求健康者',
      material: '黄铜',
      size: '高度15-30cm',
      origin: '河北安国',
      tags: ['健康', '长寿', '祛病'],
      reason: '葫芦谐音"福禄"，可收纳病气、纳福聚财，摆放床头有益健康。'
    },
    {
      id: 'daojia-005',
      categoryId: 'daojia',
      subcategoryId: 'health',
      name: '太极图挂件',
      image: 'https://images.unsplash.com/photo-1599901860904-17e9eddb3b46?w=400&h=400&fit=crop',
      price: '结缘 88-388',
      rating: 4.8,
      sales: 5678,
      description: '阴阳调和，太极圆满，身心平衡',
      effects: '调和阴阳、平衡身心、增强能量',
      suitable: '身心失衡者、修行者、追求和谐者',
      material: '玉/铜/木质',
      size: '直径3-8cm',
      origin: '河南洛阳',
      tags: ['平衡', '调和', '养生'],
      reason: '太极图为道家标志，象征阴阳调和，佩戴可平衡身心、增强能量。'
    },

    // ===== 名医名方 =====
    {
      id: 'yifang-001',
      categoryId: 'yifang',
      subcategoryId: 'wanji',
      name: '六味地黄丸（仲景）',
      image: '💊',
      price: '结缘 68-128',
      rating: 4.9, premium: true,
      sales: 50000,
      description: '补肾经典，滋阴降火，养生圣品',
      effects: '滋阴补肾、改善腰膝酸软、提升精力',
      suitable: '肾阴虚者、腰膝酸软者、中老年人',
      material: '熟地黄、山茱萸、山药等',
      size: '每瓶200-360丸',
      origin: '河南南阳（仲景宛西制药）',
      tags: ['补肾', '滋阴', '经典'],
      reason: '六味地黄丸为补肾经典方，源自宋代钱乙《小儿药证直诀》，经仲景品牌传承，品质可靠。'
    },
    {
      id: 'yifang-002',
      categoryId: 'yifang',
      subcategoryId: 'wanji',
      name: '逍遥丸（同仁堂）',
      image: '💊',
      price: '结缘 48-88',
      rating: 4.8,
      sales: 45000,
      description: '疏肝解郁，调和肝脾，女性良药',
      effects: '疏肝解郁、改善情绪、调理月经',
      suitable: '肝气郁结者、情绪不佳者、女性调理',
      material: '柴胡、当归、白芍等',
      size: '每瓶100-200丸',
      origin: '北京（同仁堂）',
      tags: ['疏肝', '解郁', '女性'],
      reason: '逍遥丸为女性调理经典方，源自宋代《太平惠民和剂局方》，疏肝解郁效果显著。'
    },
    {
      id: 'yifang-003',
      categoryId: 'yifang',
      subcategoryId: 'wanji',
      name: '归脾丸（同仁堂）',
      image: '💊',
      price: '结缘 58-108',
      rating: 4.8,
      sales: 38000,
      description: '益气健脾，养血安神，失眠良药',
      effects: '健脾养血、改善失眠、增强记忆',
      suitable: '心脾两虚者、失眠多梦者、记忆力下降者',
      material: '党参、白术、黄芪等',
      size: '每瓶100-200丸',
      origin: '北京（同仁堂）',
      tags: ['健脾', '养血', '失眠'],
      reason: '归脾丸为健脾养血经典方，源自宋代《济生方》，对心脾两虚所致失眠效果尤佳。'
    },
    {
      id: 'yifang-004',
      categoryId: 'yifang',
      subcategoryId: 'gaofang',
      name: '秋梨膏（同仁堂）',
      image: '🍯',
      price: '结缘 68-168',
      rating: 4.9, premium: true,
      sales: 67000,
      description: '润肺止咳，生津利咽，秋燥克星',
      effects: '润肺止咳、生津止渴、清热化痰',
      suitable: '肺热咳嗽者、咽喉不适者、秋燥时节',
      material: '秋梨、蜂蜜、贝母等',
      size: '每瓶200-400g',
      origin: '北京（同仁堂）',
      tags: ['润肺', '止咳', '秋季'],
      reason: '秋梨膏为润肺止咳良方，源自清代宫廷配方，秋季服用可润燥养肺。'
    },
    {
      id: 'yifang-005',
      categoryId: 'yifang',
      subcategoryId: 'gaofang',
      name: '龟苓膏（致中和）',
      image: '🍮',
      price: '结缘 28-58',
      rating: 4.7,
      sales: 89000,
      description: '清热解毒，滋阴润燥，岭南名产',
      effects: '清热解毒、滋阴润燥、美容养颜',
      suitable: '体内有热者、皮肤干燥者、养生人士',
      material: '龟板、土茯苓、金银花等',
      size: '每盒200-400g',
      origin: '广东广州',
      tags: ['清热', '滋阴', '美容'],
      reason: '龟苓膏为岭南传统药膳，清热解毒、滋阴润燥，夏季食用尤为适宜。'
    },
    {
      id: 'yifang-006',
      categoryId: 'yifang',
      subcategoryId: 'gaofang',
      name: '阿胶糕（东阿）',
      image: '🍫',
      price: '结缘 168-588',
      rating: 4.9, premium: true,
      sales: 78000,
      description: '补血滋阴，美容养颜，女性圣品',
      effects: '补血养颜、改善气血、调理月经',
      suitable: '气血两虚者、女性调理、产后恢复',
      material: '阿胶、核桃、黑芝麻等',
      size: '每盒250-500g',
      origin: '山东东阿',
      tags: ['补血', '养颜', '女性'],
      reason: '阿胶为补血圣药，源自《神农本草经》，东阿阿胶为正宗道地产区，品质上乘。'
    },
    {
      id: 'yifang-007',
      categoryId: 'yifang',
      subcategoryId: 'mingyi',
      name: '李时珍养生茶',
      image: '🍵',
      price: '结缘 68-168',
      rating: 4.8,
      sales: 45000,
      description: '药圣配方，调理五脏，养生佳品',
      effects: '调理五脏、养生保健、延年益寿',
      suitable: '养生人士、中老年人、亚健康者',
      material: '枸杞、菊花、决明子等',
      size: '每盒100-200g',
      origin: '湖北蕲春',
      tags: ['养生', '调理', '药圣'],
      reason: '李时珍为明代药圣，此配方源自《本草纲目》，综合调理五脏、养生保健。'
    },
    {
      id: 'yifang-008',
      categoryId: 'yifang',
      subcategoryId: 'mingyi',
      name: '张仲景四物汤',
      image: '🥣',
      price: '结缘 88-188',
      rating: 4.9, premium: true,
      sales: 34000,
      description: '医圣名方，补血调经，妇科圣方',
      effects: '补血调经、活血化瘀、美容养颜',
      suitable: '女性调理、血虚者、月经不调者',
      material: '当归、川芎、白芍、熟地',
      size: '每盒100-200g',
      origin: '河南南阳',
      tags: ['补血', '调经', '妇科'],
      reason: '四物汤源自医圣张仲景《金匮要略》，为补血调经第一方，女性必备。'
    },
    {
      id: 'yifang-009',
      categoryId: 'yifang',
      subcategoryId: 'mingyi',
      name: '孙思邈长寿丸',
      image: '💊',
      price: '结缘 128-288',
      rating: 4.8,
      sales: 28000,
      description: '药王秘方，延年益寿，补肾强身',
      effects: '延年益寿、补肾强身、增强免疫',
      suitable: '中老年人、体质虚弱者、养生者',
      material: '枸杞、黄精、首乌等',
      size: '每瓶100-200丸',
      origin: '陕西铜川',
      tags: ['长寿', '补肾', '强身'],
      reason: '孙思邈为唐代药王，寿逾百岁，此方为其养生秘方，补肾强身、延年益寿。'
    },

    // ===== 道医专区 =====
    {
      id: 'daoyi-001',
      categoryId: 'yifang',
      subcategoryId: 'daoyi',
      name: '张道明道长',
      image: '☯️',
      price: '面议',
      rating: 4.9, premium: true,
      sales: 0,
      origin: '江西龙虎山',
      description: '龙虎山道医协会副会长 · 玄门龙门派23代传人 · 36年临床经验',
      effects: '望诊断病、针药结合、内丹养生',
      suitable: '心脑血管病、三高症、疑难杂症、需道医调理者',
      expertise: '三通六合针法、扶阳通督法、道家养生功',
      location: '江西龙虎山',
      tags: ['道医', '内丹', '针灸'],
      reason: '张道明道长为龙虎山正一道医，结合丹道医学与现代中医，36年临床经验，擅治心脑血管等疑难杂症。'
    },
    {
      id: 'daoyi-002',
      categoryId: 'yifang',
      subcategoryId: 'daoyi',
      name: '吕微信道长',
      image: '☯️',
      price: '面议',
      rating: 4.8,
      sales: 0,
      origin: '湖北武当山',
      description: '正一派道医 · 武当山传承 · 擅针剂以意引针',
      effects: '疑难杂症、根治痼疾、调和气血',
      suitable: '久治不愈的慢性病、需道医独特疗法者',
      expertise: '古道针医、易医结合、风水命理与病症对应',
      location: '武当山',
      tags: ['道医', '针剂', '传承'],
      reason: '吕微信道长融合中医、道医、西医，取其精华，针剂以意引针、以针导气，对疑难杂症有独到疗效。'
    },
    {
      id: 'daoyi-003',
      categoryId: 'yifang',
      subcategoryId: 'daoyi',
      name: '王清川道长',
      image: '☯️',
      price: '面议',
      rating: 4.9, premium: true,
      sales: 0,
      origin: '广西南宁白鹤观',
      description: '正宗道医传承人 · 悬壶济世四十余载 · 古法养生',
      effects: '正统道医调理、古法养生、内证外养',
      suitable: '需正统道医调理、重视古法养生的修行者',
      expertise: '道医辨证施治、古法药膳、静坐导引',
      location: '广西南宁白鹤观',
      tags: ['道医', '古法', '养生'],
      reason: '王清川道长法脉纯正，四十余年潜心修道，专研正统道医与古法养生，以道立心、以医渡世。'
    },
    {
      id: 'daoyi-004',
      categoryId: 'yifang',
      subcategoryId: 'daoyi',
      name: '王传友教授',
      image: '☯️',
      price: '面议',
      rating: 4.8,
      sales: 0,
      origin: '北京白云观',
      description: '乾隆御医第六代传人 · 御医王天和家族 · 五十余年临床',
      effects: '中西医结合、整骨复位、鬼门十三针',
      suitable: '肿瘤、骨科顽疾、需祖传绝技治疗者',
      expertise: '鬼门十三针、王氏整骨、中医整体观念',
      location: '北京',
      tags: ['道医', '御医', '传承'],
      reason: '王传友为乾隆御医第六代传人，承袭鬼门十三针及王氏整骨秘术，对肿瘤、骨科等疑难杂症疗效显著。'
    },
    {
      id: 'daoyi-005',
      categoryId: 'yifang',
      subcategoryId: 'daoyi',
      name: '李坚道长（道坚散人）',
      image: '☯️',
      price: '面议',
      rating: 4.7,
      sales: 0,
      origin: '湖北武当山',
      description: '武当玄武派传承 · 悬壶济世 · 祝由术传人',
      effects: '易学风水、气功祝由、太极养生',
      suitable: '需祝由治病、风水调理、武当功法修炼者',
      expertise: '祝由治病、开天眼查事、易学风水',
      location: '武当山',
      tags: ['道医', '祝由', '武当'],
      reason: '李坚道长师承武当玄武派，集道家医学与易学风水于一身，祝由术治病、太极养生，惠及有缘众生。'
    },

    // ===== 佛医专区 =====
    {
      id: 'foyi-001',
      categoryId: 'yifang',
      subcategoryId: 'foyi',
      name: '宽恒法师',
      image: '🙏',
      price: '面议',
      rating: 4.9, premium: true,
      sales: 0,
      origin: '湖北武汉归元寺',
      description: '佛医高僧 · 施今墨门下 · 用果蔬花草疗愈身心',
      effects: '身心疗愈、慈悲心调养、禅修指导',
      suitable: '心理困扰、需禅修指导、愿以佛法调心者',
      expertise: '果蔬疗愈、禅修引导、佛法心理疗法',
      location: '汉口',
      tags: ['佛医', '禅修', '疗愈'],
      reason: '宽恒法师为佛门高医，将中医与佛学智慧结合，用果蔬花草自然疗愈身心，体现医者慈悲之心。'
    },
    {
      id: 'foyi-002',
      categoryId: 'yifang',
      subcategoryId: 'foyi',
      name: '李应存教授',
      image: '🙏',
      price: '面议',
      rating: 4.9, premium: true,
      sales: 0,
      origin: '甘肃兰州',
      description: '敦煌医学名家 · 佛医道医 · 金扁鹊中医百强',
      effects: '敦煌医学方、佛医与道医结合、内科妇科儿科',
      suitable: '肝肾病、咳嗽、白细胞减少等需敦煌医学调理者',
      expertise: '敦煌医学文献与临床、佛医道医研究、子午流注',
      location: '甘肃兰州（甘肃中医药大学附属医院）',
      tags: ['佛医', '敦煌', '金扁鹊'],
      reason: '李应存教授为敦煌医学学科带头人，研究佛医与道医，临床善用敦煌医学方，获2025金扁鹊全国中医百强。'
    },
    {
      id: 'foyi-003',
      categoryId: 'yifang',
      subcategoryId: 'foyi',
      name: '瞿俊署（风云居士）',
      image: '🙏',
      price: '面议',
      rating: 4.8,
      sales: 0,
      origin: '福建莆田少林寺',
      description: '广东省悟真传承医学研究院院长 · 摸骨诊断第九代传人',
      effects: '少林禅医、分筋挫骨手、中医全科',
      suitable: '颈椎腰椎骨病、肿瘤调理、需少林禅医疗法者',
      expertise: '摸骨诊断病、祖传正骨、少林悟真法师传承',
      location: '广东',
      tags: ['佛医', '少林', '正骨'],
      reason: '瞿俊署居士师承少林悟真法师，传承祖上秘方，结合佛家医理，分筋挫骨手对骨关节疾病疗效显著。'
    },
    {
      id: 'foyi-004',
      categoryId: 'yifang',
      subcategoryId: 'foyi',
      name: '孙思邈（药王）',
      image: '🙏',
      price: '面议',
      rating: 4.9, premium: true,
      sales: 0,
      origin: '陕西铜川药王山',
      description: '唐代药王 · 被尊为药师佛化身 · 药王《千金方》作者',
      effects: '养生延寿、疑难杂症、慈悲济世',
      suitable: '追求长寿养生、需药王智慧调养者',
      expertise: '本草研究、养生秘方、大医精诚',
      location: '陕西铜川（药王山）',
      tags: ['药王', '养生', '历史'],
      reason: '孙思邈为唐代著名道医，被后人尊为药师佛化身，寿逾百岁，《千金方》为中医学巨著，泽被后世。'
    },
    {
      id: 'foyi-005',
      categoryId: 'yifang',
      subcategoryId: 'foyi',
      name: '释通林禅师',
      image: '🙏',
      price: '面议',
      rating: 4.7,
      sales: 0,
      origin: '福建莆田少林寺',
      description: '少林寺禅医传承 · 一级医师 · 百病克星金奖获得者',
      effects: '禅医调理、体控疗法、筋骨经络',
      suitable: '需少林禅医疗法、体控经络调理者',
      expertise: '禅医体控疗法、少林功夫养生',
      location: '福建莆田（少林寺）',
      tags: ['禅医', '少林', '体控'],
      reason: '释通林禅师融合少林禅修与中医，形成独特禅医体系，体控疗法对多种疾病有显著疗效。'
    },

    // ===== 儒家经典 =====
    {
      id: 'ru-jing-001',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '论语（注疏版）',
      image: '📕',
      price: '结缘 128',
      originalPrice: '¥168',
      rating: 4.9, premium: true,
      sales: 8652,
      author: '孔子·述 / 何晏·集解 / 邢昺·疏',
      description: '《论语》为儒家至高经典，记录孔子及其弟子言行，涵盖修身、齐家、治国、平天下之大义。此版以十三经注疏本为底本，详加校勘，注释精当，白话译文流畅易懂，适合深度研读。',
      effects: '明仁义礼智信之旨，悟修齐治平之道',
      suitable: '国学爱好者、传统文化研习者、大学生',
      tags: ['必读', '注疏版', '入门'],
      reason: '半部《论语》治天下。读《论语》可知为人之道、为学之法、为政之理，是儒家入门必读经典。'
    },
    {
      id: 'ru-jing-002',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '论语（白话版）',
      image: '📘',
      price: '结缘 48',
      originalPrice: '¥68',
      rating: 4.8,
      sales: 12450,
      author: '孔子·述 / 钱穆·译注',
      description: '钱穆先生白话译注版《论语》，语言通俗流畅，保留原文韵味的同时降低阅读门槛。每章附有简要解读，帮助读者理解孔子思想精髓。适合初次接触儒学的读者。',
      effects: '浅显易懂地理解儒家核心思想',
      suitable: '初学者、中学生、大众读者',
      tags: ['入门', '白话版'],
      reason: '钱穆先生学贯中西，其白话译注既忠实原意又通俗易懂，是初读《论语》的最佳选择。'
    },
    {
      id: 'ru-jing-003',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '大学·中庸（合订本）',
      image: '📗',
      price: '结缘 58',
      rating: 4.9, premium: true,
      sales: 6320,
      author: '曾子·子思 / 朱熹·章句',
      description: '《大学》述修齐治平之序，《中庸》论至诚尽性之道。二书为四书之首，篇幅虽短却义理精深。此合订本采用朱子章句本，附白话翻译及历代名家解读，便于对照研读。',
      effects: '知止定静安虑得之次第，悟中和位育之境界',
      suitable: '国学入门者、修身爱好者',
      tags: ['必读', '入门'],
      reason: '《大学》立规模、《中庸》极精微，二书合读可得儒学修养之全貌。'
    },
    {
      id: 'ru-jing-004',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '孟子',
      image: '📕',
      price: '结缘 98',
      originalPrice: '¥128',
      rating: 4.8,
      sales: 5840,
      author: '孟子·述 / 赵岐·注 / 焦循·正义',
      description: '《孟子》七篇，述性善、仁政、义利之辨，雄辩滔滔，气势磅礴。此版以焦循《孟子正义》为底本，汇集历代注疏精华，附现代白话翻译，为研读孟学之善本。',
      effects: '养浩然正气，明性善之旨',
      suitable: '儒学研究者、传统文化爱好者',
      tags: ['必读', '注疏版'],
      reason: '孟子发展孔子学说，提出性善论、仁政思想，对中国文化影响深远，不可不读。'
    },
    {
      id: 'ru-jing-005',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '诗经',
      image: '📙',
      price: '结缘 108',
      rating: 4.7,
      sales: 4260,
      author: '佚名 / 毛亨·传 / 郑玄·笺',
      description: '《诗经》为中国最早诗歌总集，收诗305篇，分风雅颂三类。此版以《毛诗正义》为底本，含全文注释、白话翻译及诗旨解读，并附古韵考释，文学与史学价值兼具。',
      effects: '感发志意，考见得失，多识草木鸟兽之名',
      suitable: '文学爱好者、古典诗词研习者',
      tags: ['必读', '注疏版'],
      reason: '不学诗无以言。《诗经》为儒家五经之首，既是文学源头，亦是了解先秦社会之窗口。'
    },
    {
      id: 'ru-jing-006',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '尚书',
      image: '📕',
      price: '结缘 118',
      rating: 4.6,
      sales: 2840,
      author: '孔子·编 / 孔安国·传',
      description: '《尚书》为中国最早史书，记载尧舜至周代政事。此版以孔传古文尚书为底本，附今译及历代考辨，虽经清代辨伪之争，其史料价值与思想价值仍不可低估。',
      effects: '明先王政教之体，知历代兴替之由',
      suitable: '史学研究者、古文献爱好者',
      tags: ['进阶', '注疏版'],
      reason: '《尚书》为政书之祖，读之可了解上古政治理念与治国方略。'
    },
    {
      id: 'ru-jing-007',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '礼记',
      image: '📗',
      price: '结缘 138',
      originalPrice: '¥168',
      rating: 4.7,
      sales: 3120,
      author: '戴圣·编 / 郑玄·注 / 孔颖达·疏',
      description: '《礼记》为先秦至秦汉礼仪制度文献汇编，含《大学》《中庸》《礼运》等名篇。此版以《礼记正义》为底本，选录精华篇章，注释详备，白话翻译准确，为了解中华礼乐文明之要籍。',
      effects: '知礼明仪，修身正己',
      suitable: '礼学研究者、传统文化爱好者',
      tags: ['进阶', '注疏版'],
      reason: '礼为中华文明之骨架，《礼记》记录大量礼制与人生哲理，是理解中国文化深层结构的钥匙。'
    },
    {
      id: 'ru-jing-008',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '周易本义（朱熹）',
      image: '📘',
      price: '结缘 88',
      rating: 4.9, premium: true,
      sales: 7680,
      author: '朱熹·撰',
      description: '朱熹《周易本义》为宋代理学解易代表作，以义理为主兼取象数，力求还原《周易》本义。此版含原文、朱子注解及白话翻译，并附朱子易学纲领导读，为研习易理之善本。',
      effects: '明阴阳消长之理，知进退存亡之道',
      suitable: '易学爱好者、理学研究者',
      tags: ['必读', '进阶'],
      reason: '朱子解易立足义理，简明扼要，为后世科举定本，影响深远，适合系统研习《周易》。'
    },
    {
      id: 'ru-jing-009',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '春秋左传',
      image: '📙',
      price: '结缘 148',
      originalPrice: '¥188',
      rating: 4.8,
      sales: 3920,
      author: '左丘明·撰 / 杜预·注',
      description: '《左传》为《春秋》三传之一，以丰富史事阐释《春秋》微言大义。叙事生动，文辞优美，为先秦散文之巅峰。此版含全文注释及白话翻译，并附春秋大事年表及地图，便于阅读。',
      effects: '明春秋大义，鉴历史兴替',
      suitable: '史学爱好者、古文学习者',
      tags: ['进阶', '注疏版'],
      reason: '《左传》不仅为史学名著，更为古文典范，读之可同时提升史学素养与古文水平。'
    },
    {
      id: 'ru-jing-010',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '孝经',
      image: '📕',
      price: '结缘 38',
      rating: 4.6,
      sales: 5230,
      author: '孔子·述 / 唐玄宗·注',
      description: '《孝经》十八章，以孝为核心，论述孝为德之本、教之所由生。篇幅短小而义理深远，历代帝王多为之作注。此版含唐玄宗御注及白话翻译，并附历代孝行故事选编。',
      effects: '明孝道大义，知修身立本',
      suitable: '国学入门者、家庭教育',
      tags: ['入门', '必读'],
      reason: '百善孝为先。《孝经》篇幅短小易读，是了解儒家伦理思想的入门捷径。'
    },
    {
      id: 'ru-jing-011',
      categoryId: 'jingdian',
      subcategoryId: 'rujia-jing',
      name: '近思录',
      image: '📗',
      price: '结缘 68',
      rating: 4.7,
      sales: 2180,
      author: '朱熹·吕祖谦·编',
      description: '《近思录》为朱熹、吕祖谦合编的北宋四子（周敦颐、程颢、程颐、张载）语录摘编，分十四卷，系统呈现理学思想体系。此版含原文、注释及白话翻译，并附理学概念诠释索引。',
      effects: '明理学纲领，知修身次第',
      suitable: '理学研究者、修身爱好者',
      tags: ['进阶'],
      reason: '《近思录》为理学入门阶梯，编选精当，可窥北宋四子思想全貌。'
    },

    // ===== 道家经典 =====
    {
      id: 'dao-jing-001',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '道德经（注疏版）',
      image: '📜',
      price: '结缘 98',
      originalPrice: '¥128',
      rating: 5.0, premium: true,
      sales: 15620,
      author: '老子·撰 / 王弼·注 / 河上公·注',
      description: '《道德经》五千言，为道家至高经典，论述道体德用、无为而治、柔弱胜刚强等思想。此版汇集王弼注、河上公注及历代名家疏解，附白话翻译及帛书本对照，为研习老学之集大成善本。',
      effects: '悟道法自然之旨，明无为而无不为之道',
      suitable: '道家文化爱好者、哲学研究者、修身人士',
      tags: ['必读', '注疏版'],
      reason: '《道德经》为万经之王，涵盖哲学、政治、修身、养生等智慧，值得一生研读。'
    },
    {
      id: 'dao-jing-002',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '道德经（白话版）',
      image: '📄',
      price: '结缘 42',
      rating: 4.9, premium: true,
      sales: 18930,
      author: '老子·撰 / 陈鼓应·译注',
      description: '陈鼓应先生《老子今注今译》，以王弼本为底本，参校帛书甲乙本及楚简本，注释详明，译文流畅。每章附有解题及要点分析，为现代读者打开《道德经》智慧之门的最佳版本。',
      effects: '轻松读懂老子智慧',
      suitable: '初学者、大众读者',
      tags: ['入门', '白话版'],
      reason: '陈鼓应先生为当代老学权威，其译注既学术严谨又通俗易懂，强烈推荐入门者。'
    },
    {
      id: 'dao-jing-003',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '庄子（南华经）',
      image: '📙',
      price: '结缘 118',
      originalPrice: '¥158',
      rating: 4.9, premium: true,
      sales: 8740,
      author: '庄子·撰 / 郭象·注 / 陈鼓应·今译',
      description: '《庄子》三十三篇，文风汪洋恣肆，想象奇绝，述逍遥齐物、养生处世之道。此版以郭象本为底本，含全文注释、白话翻译及陈鼓应先生解题导读，并附庄子哲学体系概览。',
      effects: '达逍遥之境，齐物我之分',
      suitable: '哲学爱好者、文学爱好者',
      tags: ['必读', '注疏版'],
      reason: '《庄子》为道家第二经典，其文学价值与哲学深度在先秦诸子中无出其右。'
    },
    {
      id: 'dao-jing-004',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '列子',
      image: '📕',
      price: '结缘 78',
      rating: 4.7,
      sales: 3420,
      author: '列子·撰 / 张湛·注',
      description: '《列子》八篇，述列子哲理思想，含愚公移山、杞人忧天等寓言。此版以张湛注本为底本，附白话翻译及寓言故事解读，并考辨真伪篇目，为了解道家思想另一维度之要籍。',
      effects: '明虚静无为之道，悟物我两忘之境',
      suitable: '道家文化爱好者',
      tags: ['进阶'],
      reason: '《列子》在道家地位仅次于老庄，其寓言故事通俗易懂，富有哲理。'
    },
    {
      id: 'dao-jing-005',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '黄帝阴符经',
      image: '📜',
      price: '结缘 58',
      rating: 4.8,
      sales: 4150,
      author: '佚名 / 李筌·注',
      description: '《阴符经》三百余字，为道家重要经典，论述天地人三才相盗之理、阴阳机变之道。文简义深，历来注家众多。此版汇集李筌、张果老、朱熹等七家注解，附白话翻译及义理辨析。',
      effects: '明天地机变之理，察造化消息之机',
      suitable: '道家修习者、术数爱好者',
      tags: ['进阶', '必读'],
      reason: '《阴符经》字字珠玑，虽简短却蕴含深奥哲理，为道家修炼与兵法谋略之纲领。'
    },
    {
      id: 'dao-jing-006',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '周易参同契',
      image: '📗',
      price: '结缘 88',
      rating: 4.6,
      sales: 2380,
      author: '魏伯阳·撰 / 朱熹·考异',
      description: '《周易参同契》为道家丹道之祖经，以周易卦象、黄老之道、炉火之法三家相参而成。此版含原文、注释及白话翻译，并附丹道术语词典与卦象对照表，为研习内丹学之必读。',
      effects: '明丹道纲领，知修炼次第',
      suitable: '丹道修习者、道家文化深度爱好者',
      tags: ['进阶', '必读'],
      reason: '《参同契》被尊为万古丹经王，为内丹修炼之根本经典，修真者不可不读。'
    },
    {
      id: 'dao-jing-007',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '抱朴子',
      image: '📘',
      price: '结缘 108',
      originalPrice: '¥138',
      rating: 4.7,
      sales: 2640,
      author: '葛洪·撰',
      description: '《抱朴子》分内外篇，内篇述神仙丹道、养生方术，外篇论时政人事。为研究晋代道教及方术之重要文献。此版含全文注释及白话翻译，并附葛洪生平及道教史背景介绍。',
      effects: '知道家方术概貌，明养生修炼之法',
      suitable: '道教研究者、养生爱好者',
      tags: ['进阶'],
      reason: '《抱朴子》保存了大量古代方术与炼丹资料，为了解道教实践传统之必读。'
    },
    {
      id: 'dao-jing-008',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '黄庭经',
      image: '📄',
      price: '结缘 48',
      rating: 4.6,
      sales: 3260,
      author: '佚名 / 魏华存·传',
      description: '《黄庭经》分内外景，以七言韵文论述五脏神明及存思修炼之法，为道教内丹修炼之重要经典。此版含原文、注释及白话翻译，并附脏腑神明图谱及存思法图解。',
      effects: '明脏腑神明之理，知存思修炼之法',
      suitable: '丹道修习者、中医爱好者',
      tags: ['进阶'],
      reason: '《黄庭经》为道教上清派核心经典，对内丹学发展影响深远，修真者必读。'
    },
    {
      id: 'dao-jing-009',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '太上感应篇',
      image: '📜',
      price: '结缘 38',
      rating: 4.8,
      sales: 6850,
      author: '佚名 / 李昌龄·传',
      description: '《太上感应篇》为道教善书之首，以因果报应之说劝人行善积德。篇幅短小，文辞浅白，影响极为广泛。此版含原文、白话翻译及因果故事选编，并附历代灵验记。',
      effects: '知善恶报应之理，明积德行善之要',
      suitable: '大众读者、道教信众',
      tags: ['入门', '必读'],
      reason: '《感应篇》为善书第一经典，简明易懂，为儒道佛共尊之劝善宝典。'
    },
    {
      id: 'dao-jing-010',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '文昌帝君阴骘文',
      image: '📕',
      price: '结缘 36',
      rating: 4.7,
      sales: 5120,
      author: '佚名',
      description: '《文昌帝君阴骘文》为道教重要善书，以文昌帝君口吻劝人广行阴骘、积德行善。文辞简练，意蕴深远，与《感应篇》《觉世真经》并称三大善书。此版含注释、白话翻译及灵验故事。',
      effects: '明阴骘之理，行善积德',
      suitable: '大众读者、道教信众',
      tags: ['入门'],
      reason: '《阴骘文》简短易读，是了解道教伦理思想及善书传统的入门读物。'
    },
    {
      id: 'dao-jing-011',
      categoryId: 'jingdian',
      subcategoryId: 'daojia-jing',
      name: '性命圭旨',
      image: '📗',
      price: '结缘 78',
      originalPrice: '¥98',
      rating: 4.8,
      sales: 2980,
      author: '佚名 / 尹真人·秘授',
      description: '《性命圭旨》为明代内丹学集大成之作，分元亨利贞四集，详述性命双修之理法，附大量修炼图说。此版含原文、注释及白话翻译，并附内丹术语词典与功法图解。',
      effects: '明性命双修之理，知内丹修炼全法',
      suitable: '丹道修习者、道家养生爱好者',
      tags: ['进阶', '必读'],
      reason: '《性命圭旨》系统完整地呈现内丹修炼次第，为修真者之实用指南。'
    },

    // ===== 佛家经典 =====
    {
      id: 'fo-jing-001',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '金刚经',
      image: '📜',
      price: '结缘 58',
      rating: 5.0, premium: true,
      sales: 18560,
      author: '鸠摩罗什·译 / 江味农·校释',
      description: '《金刚般若波罗蜜经》为大乘佛教核心经典，述般若空义，破一切相执。此版以鸠摩罗什译本为底本，附江味农居士校释及白话翻译，并含历代注疏精选，为研习般若法门之善本。',
      effects: '破相显性，悟无住生心之旨',
      suitable: '佛学入门者、禅修爱好者',
      tags: ['必读', '入门'],
      reason: '《金刚经》为中国佛教流传最广的经典之一，禅宗所依根本经典，读之可破执著、开智慧。'
    },
    {
      id: 'fo-jing-002',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '心经（般若波罗蜜多心经）',
      image: '📄',
      price: '结缘 36',
      rating: 5.0, premium: true,
      sales: 22340,
      author: '玄奘·译 / 圆瑛·讲义',
      description: '《心经》仅二百六十字，浓缩六百卷《大般若经》精华，述五蕴皆空、色空不二之理。此版以玄奘译本为底本，附圆瑛法师讲义及白话翻译，并含历代书法名家写经赏析。',
      effects: '悟色空不二之理，证般若真空之智',
      suitable: '佛学入门者、大众读者',
      tags: ['必读', '入门'],
      reason: '《心经》为佛经中字数最少却义理最深者，为一切佛法的精髓，读经首选。'
    },
    {
      id: 'fo-jing-003',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '地藏菩萨本愿经',
      image: '📙',
      price: '结缘 58',
      rating: 4.9, premium: true,
      sales: 9870,
      author: '实叉难陀·译',
      description: '《地藏经》述地藏菩萨因地发愿及孝道度生事迹，强调因果报应、孝亲尊师。为佛教孝经，民间影响极广。此版含全文注释、白话翻译及地藏法门修持指引。',
      effects: '明因果报应之理，发孝亲度生之愿',
      suitable: '佛学入门者、地藏法门修持者',
      tags: ['必读', '入门'],
      reason: '《地藏经》为学佛入门第一经，明因果、重孝道，适合初学佛者建立正见。'
    },
    {
      id: 'fo-jing-004',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '妙法莲华经',
      image: '📕',
      price: '结缘 88',
      originalPrice: '¥118',
      rating: 4.9, premium: true,
      sales: 5230,
      author: '鸠摩罗什·译 / 智者·疏',
      description: '《法华经》为大乘佛教重要经典，述一乘佛法、会三归一之旨，含方便品、譬喻品等名篇。天台宗依此立宗。此版含全文注释、白话翻译及天台宗义理概览。',
      effects: '悟一乘真实之旨，开示悟入佛之知见',
      suitable: '佛学进阶者、天台宗学习者',
      tags: ['进阶', '必读'],
      reason: '《法华经》为大乘经典之王，述成佛之道的终极教义，为天台宗根本经典。'
    },
    {
      id: 'fo-jing-005',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '楞严经',
      image: '📗',
      price: '结缘 98',
      rating: 4.8,
      sales: 4180,
      author: '般剌密帝·译 / 虚云·讲要',
      description: '《楞严经》述阿难遭难、佛陀说法破妄显真，详论二十五圆通及楞严咒。为禅宗、净土宗共尊之要典。此版含全文注释、白话翻译及虚云老和尚讲要摘要。',
      effects: '破妄显真，明心见性',
      suitable: '禅修者、佛学进阶者',
      tags: ['进阶', '必读'],
      reason: '自古云「开慧楞严」，《楞严经》为开发智慧、明心见性之要典，修禅者必读。'
    },
    {
      id: 'fo-jing-006',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '华严经',
      image: '📘',
      price: '结缘 168',
      originalPrice: '¥228',
      rating: 4.9, premium: true,
      sales: 2860,
      author: '实叉难陀·译 / 法藏·疏',
      description: '《华严经》为经王，述毗卢遮那佛法界境界，含善财童子五十三参等名篇。华严宗依此立宗。此版为八十华严精选本，含注释、白话翻译及华严宗义理体系概览。',
      effects: '入法界缘起之境，悟一即一切之理',
      suitable: '佛学深度研习者、华严宗学习者',
      tags: ['进阶'],
      reason: '《华严经》为经中之王，境界宏大，义理圆融，读之可开阔心量、悟法界观。'
    },
    {
      id: 'fo-jing-007',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '阿弥陀经',
      image: '📄',
      price: '结缘 38',
      rating: 4.9, premium: true,
      sales: 8420,
      author: '鸠摩罗什·译 / 蕅益·要解',
      description: '《阿弥陀经》述西方极乐世界依正庄严及念佛往生法门，为净土宗三经之一。此版含原文、蕅益大师《弥陀要解》及白话翻译，并附念佛方法指引。',
      effects: '信愿念佛，往生净土',
      suitable: '净土法门修持者、佛学入门者',
      tags: ['必读', '入门'],
      reason: '《阿弥陀经》为净土宗根本经典，修净土法门者必读，亦为初学佛者推荐。'
    },
    {
      id: 'fo-jing-008',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '六祖坛经',
      image: '📙',
      price: '结缘 58',
      originalPrice: '¥78',
      rating: 5.0, premium: true,
      sales: 11280,
      author: '慧能·述 / 法海·记',
      description: '《六祖坛经》为唯一中国僧人所述而被尊为「经」的典籍，述禅宗六祖慧能生平及开示法语。此版含原文、注释及白话翻译，并附禅宗史脉络及五家七宗简介。',
      effects: '明顿悟法门，知自性本清净',
      suitable: '禅修爱好者、佛学入门者',
      tags: ['必读', '入门'],
      reason: '《坛经》为中国禅宗根本经典，述顿悟法门，读之可明心见性、直指本源。'
    },
    {
      id: 'fo-jing-009',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '百喻经',
      image: '📗',
      price: '结缘 42',
      rating: 4.7,
      sales: 6540,
      author: '僧伽斯那·撰 / 求那毗地·译',
      description: '《百喻经》收录九十八则寓言故事，以生动比喻阐述佛理，寓教于乐。故事简短有趣，寓意深刻。此版含原文、白话翻译及佛理解读，并附插画。',
      effects: '以喻明理，轻松领悟佛理',
      suitable: '初学者、青少年、大众读者',
      tags: ['入门'],
      reason: '《百喻经》以故事说法，通俗易懂，为佛学入门之趣味读物。'
    },
    {
      id: 'fo-jing-010',
      categoryId: 'jingdian',
      subcategoryId: 'fojia-jing',
      name: '维摩诘经',
      image: '📕',
      price: '结缘 68',
      rating: 4.8,
      sales: 4320,
      author: '鸠摩罗什·译 / 僧肇·注',
      description: '《维摩诘经》述在家居士维摩诘示疾说法，以不二法门破二乘执著。此经融合世间与出世间，为大乘佛教居士修行之典范。此版含原文、注释及白话翻译，并附僧肇注摘要。',
      effects: '悟不二法门，明在家修行之道',
      suitable: '居士修行者、佛学进阶者',
      tags: ['进阶', '必读'],
      reason: '《维摩诘经》为大乘经典中居士修行之典范，述不二法门，文辞优美，义理圆融。'
    },

    // ═══════════════════════════════════════
    // ===== 滋补养生 =====
    // ═══════════════════════════════════════
    // 参茸贵细
    {
      id: 'zs-001',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'renshen-lei',
      name: '长白山野山参（林下山参）',
      image: '🌿',
      price: '结缘 688-8888',
      rating: 4.9, premium: true,
      sales: 3256,
      description: '长白山原始森林林下山参，自然生长15年以上，芦长体灵，纹细须清，大补元气',
      effects: '大补元气、复脉固脱、补脾益肺、生津养血、安神益智',
      suitable: '气血不足、体虚乏力、术后恢复、免疫力低下者',
      element: '土',
      usage: '炖服：切片文火慢炖2小时。含服：薄片含于舌下。泡酒：500ml白酒浸泡2周',
      storage: '阴凉干燥处密封保存，防潮防虫蛀，鲜参加苔藓冷藏',
      taboo: '实热证及阴虚火旺者慎用，不宜与萝卜浓茶同食，高血压遵医嘱',
      material: '长白山原始森林林下山参',
      size: '重量5g-50g可选',
      origin: '吉林长白山（国家地理标志产品）',
      certification: '国家地理标志产品·长白山人参',
      tags: ['大补元气', '参茸', '长白山']
    },
    {
      id: 'zs-002',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'renshen-lei',
      name: '鹿茸片（梅花鹿茸）',
      image: '🦌',
      price: '结缘 388-2888',
      rating: 4.8,
      sales: 4215,
      description: '东北梅花鹿茸蜡片/粉片/血片精选，含丰富氨基酸和生长因子，壮阳补肾强筋骨',
      effects: '壮肾阳、益精血、强筋骨、调冲任、托疮毒',
      suitable: '肾阳不足、精血亏虚、腰膝酸软、畏寒怕冷者',
      element: '火',
      usage: '研粉冲服：每日0.5-1g。泡酒：10g泡500ml白酒。炖汤：2-3g入汤',
      storage: '密封冷藏保存（0-4°C），忌受潮及虫蛀',
      taboo: '阴虚阳亢、血热、外感热病者禁用，不宜超量久服',
      material: '梅花鹿（Cervus nippon）蜡片/粉片',
      size: '包装10g-50g',
      origin: '吉林长春（梅花鹿之乡）',
      certification: '国家林业局许可·合法养殖',
      tags: ['补肾壮阳', '参茸', '鹿茸']
    },
    {
      id: 'zs-003',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'renshen-lei',
      name: '高丽红参（六年根）',
      image: '🫚',
      price: '结缘 288-1688',
      rating: 4.9, premium: true,
      sales: 5892,
      description: '韩国高丽参六年根红参，蒸制工艺，温补性佳，适合虚寒体质温养',
      effects: '温补元气、复脉固脱、益气摄血、增强免疫',
      suitable: '阳虚体质、手脚冰凉、术后体虚、免疫力低下者',
      element: '火',
      usage: '切片含服：每次2-3片。炖汤：5-10g。泡茶：3-5g沸水冲泡',
      storage: '密封阴凉干燥处保存，防虫防霉',
      taboo: '阴虚火旺及实热证者禁用，不宜与藜芦同用',
      material: '高丽参（Panax ginseng）六年根',
      size: '净重37.5g-150g',
      origin: '韩国锦山/扶余（原装进口）',
      certification: '韩国人参公社认证·KGC',
      tags: ['温补', '参茸', '高丽参']
    },
    // 灵芝孢子
    {
      id: 'zs-004',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'lingzhi-lei',
      name: '破壁灵芝孢子粉',
      image: '🍄',
      price: '结缘 198-888',
      rating: 4.8,
      sales: 7892,
      description: '大别山椴木灵芝孢子粉，超低温物理破壁技术，破壁率≥98%，易吸收三萜和多糖',
      effects: '扶正固本、养心安神、增强免疫、辅助抗癌康复',
      suitable: '免疫力低下、失眠多梦、肿瘤术后康复、亚健康人群',
      element: '木',
      usage: '每日2次，每次2g（一平勺），温水冲服或拌入牛奶/粥中',
      storage: '密封冷藏保存（0-8°C），开封后尽快食用',
      taboo: '孕妇慎用，对灵芝过敏者禁用，手术前后遵医嘱',
      material: '椴木灵芝（Ganoderma lucidum）孢子粉',
      size: '净含量100g-250g',
      origin: '安徽大别山（灵芝之乡）',
      certification: '有机认证·GMP标准生产',
      tags: ['扶正固本', '灵芝', '免疫']
    },
    {
      id: 'zs-005',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'lingzhi-lei',
      name: '野生灵芝切片',
      image: '🍄',
      price: '结缘 168-688',
      rating: 4.7,
      sales: 4321,
      description: '长白山野生赤灵芝切片，自然生长无农药，煲汤泡茶皆宜，养肝安神',
      effects: '养肝解毒、安神助眠、增强免疫、延缓衰老',
      suitable: '肝火旺盛、睡眠不佳、烟酒过量者',
      element: '木',
      usage: '煲汤：10-15g。泡茶：5-10g反复冲泡。泡酒：50g泡500ml白酒',
      storage: '密封阴凉干燥处保存',
      taboo: '灵芝性平偏温，体质燥热者少量使用',
      material: '野生赤灵芝（Ganoderma lucidum）',
      size: '净含量100g-300g',
      origin: '吉林长白山',
      certification: '野生采摘·无硫熏',
      tags: ['养肝', '安神', '野生']
    },
    // 虫草燕窝
    {
      id: 'zs-006',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'chongcao-lei',
      name: '冬虫夏草（那曲）',
      image: '🐛',
      price: '结缘 888-8888',
      rating: 4.9, premium: true,
      sales: 2156,
      description: '西藏那曲冬虫夏草，海拔4500米以上，虫体饱满金黄，草头短而色正，补肾益肺圣品',
      effects: '补肾益肺、止血化痰、增强免疫、抗疲劳',
      suitable: '肺肾两虚、久咳虚喘、术后恢复、体质虚弱者',
      element: '金',
      usage: '炖汤：3-5条/次与鸡鸭同炖。泡水：2-3条沸水焖泡。研粉冲服',
      storage: '密封冷藏保存（0-4°C），忌受潮，可放少量花椒防虫',
      taboo: '少年儿童不宜久服，感冒发热暂停，风湿性关节炎慎用',
      material: '冬虫夏草（Ophiocordyceps sinensis）',
      size: '按规格500条/1000条/1500条每斤',
      origin: '西藏那曲',
      certification: '国家地理标志产品·那曲冬虫夏草',
      tags: ['补肾益肺', '冬虫夏草', '那曲']
    },
    {
      id: 'zs-007',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'chongcao-lei',
      name: '印尼官燕盏',
      image: '🥣',
      price: '结缘 388-3888',
      rating: 4.9, premium: true,
      sales: 6543,
      description: '印尼加里曼丹官燕盏，天然洞穴燕窝，发头大，燕丝粗壮，滋补养颜上品',
      effects: '养阴润燥、益气补中、美容养颜、润肺止咳',
      suitable: '女性养颜、孕妇安胎、术后恢复、长期熬夜者',
      element: '水',
      usage: '温水浸泡4-6小时挑净杂毛，隔水炖20-30分钟，加冰糖/红枣调味',
      storage: '密封防潮保存，干燕窝常温避光可存2年，炖好的燕窝冷藏3天',
      taboo: '蛋白质过敏者慎用，感冒发热时暂停食用',
      material: '金丝燕（Aerodramus fuciphagus）燕窝',
      size: '净含量50g-250g',
      origin: '印尼加里曼丹（原装进口）',
      certification: '印尼检疫局出口许可·HACCP',
      tags: ['美容养颜', '燕窝', '滋补']
    },
    // 阿胶膏方
    {
      id: 'zs-008',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'ejiao-lei',
      name: '东阿阿胶（250g）',
      image: '🟤',
      price: '结缘 588-1288',
      rating: 4.9, premium: true,
      sales: 8923,
      description: '东阿阿胶·正宗道地，选用优质驴皮以东阿地下水熬制，补血滋阴圣药',
      effects: '补血滋阴、润燥止血、美容养颜、增强免疫',
      suitable: '气血两虚、月经不调、产后恢复、贫血体弱者',
      element: '土',
      usage: '烊化兑服：打粉以温水/黄酒调服。熬制阿胶糕：配核桃芝麻红枣',
      storage: '密封冷藏保存（0-8°C），忌受热受潮',
      taboo: '脾胃虚弱者少量服用，感冒发热停用，孕妇遵医嘱',
      material: '驴皮胶',
      size: '净含量250g',
      origin: '山东东阿（国家地理标志产品）',
      certification: '国家地理标志产品·东阿阿胶·OTC',
      tags: ['补血养颜', '阿胶', '东阿']
    },
    // 药膳食材
    {
      id: 'zs-009',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'yaoshan-lei',
      name: '道地枸杞子（宁夏特优）',
      image: '🔴',
      price: '结缘 58-198',
      rating: 4.8,
      sales: 12560,
      description: '宁夏中宁枸杞，粒大饱满色红，味甜少籽，养肝明目补肾精，泡茶炖汤皆宜',
      effects: '滋补肝肾、益精明目、延缓衰老、增强免疫',
      suitable: '肝肾阴虚、视力减退、精血亏虚、免疫力低下者',
      element: '木',
      usage: '泡水：10-15粒。煲汤：15-20g。煮粥：10-15g。干嚼：每日20-30粒',
      storage: '密封冷藏保存（0-4°C），防潮防虫',
      taboo: '外邪实热及脾虚泄泻者慎用',
      material: '宁夏枸杞（Lycium barbarum）',
      size: '净含量250g-500g',
      origin: '宁夏中宁（国家地理标志产品）',
      certification: '国家地理标志产品·中宁枸杞',
      tags: ['养肝明目', '枸杞', '药食同源']
    },
    {
      id: 'zs-010',
      categoryId: 'zibuyangsheng',
      subcategoryId: 'yaoshan-lei',
      name: '铁棍山药（焦作怀山药）',
      image: '🥔',
      price: '结缘 48-128',
      rating: 4.7,
      sales: 9876,
      description: '河南焦作铁棍山药，怀山药正宗品种，粉糯细腻，健脾养胃补肾气',
      effects: '补脾养胃、生津益肺、补肾涩精、增强消化',
      suitable: '脾胃虚弱、消化不良、肺虚咳喘、肾虚遗精者',
      element: '土',
      usage: '蒸食、煲汤（配排骨/鸡）、煮粥（配红枣/莲子）、炒食',
      storage: '阴凉通风处保存，鲜品勿密封以免霉变',
      taboo: '湿盛中满或有实邪者慎用',
      material: '怀山药（Dioscorea opposita）',
      size: '鲜品每箱2.5kg-5kg',
      origin: '河南焦作（国家地理标志产品）',
      certification: '国家地理标志产品·怀山药',
      tags: ['健脾养胃', '山药', '药食同源']
    },

    // ═══════════════════════════════════════
    // ===== 名茶雅韵 =====
    // ═══════════════════════════════════════
    // 绿茶
    {
      id: 'cy-001',
      categoryId: 'chayin',
      subcategoryId: 'lvcha',
      name: '西湖龙井（明前特级）',
      image: '🍃',
      price: '结缘 288-1888',
      rating: 4.9, premium: true,
      sales: 9876,
      description: '西湖核心产区明前龙井，色绿香郁味甘形美，中国十大名茶之首',
      effects: '清心明目、提神醒脑、消食利尿、抗氧化防衰老',
      suitable: '办公族、学生、养生人士、有高血压高血脂倾向者',
      element: '木',
      usage: '玻璃杯冲泡：80°C水温，3g茶叶，先注1/3水浸润，再续至七分满，头泡30秒',
      storage: '密封冷藏保存（0-5°C），铝箔袋密封防串味，开封后1月内饮完',
      taboo: '空腹不宜饮浓茶，失眠者晚间不饮，胃寒者宜饭后饮用',
      material: '龙井群体种/龙井43号',
      size: '净含量50g-250g',
      origin: '浙江杭州西湖区（国家地理标志产品）',
      certification: '国家地理标志产品·西湖龙井',
      tags: ['名茶', '绿茶', '龙井']
    },
    {
      id: 'cy-002',
      categoryId: 'chayin',
      subcategoryId: 'lvcha',
      name: '洞庭碧螺春（特级）',
      image: '🍃',
      price: '结缘 238-1288',
      rating: 4.8,
      sales: 7654,
      description: '苏州洞庭山碧螺春，卷曲如螺白毫显露，花香果味沁人心脾',
      effects: '提神益思、消食解腻、抗氧化、降脂减肥',
      suitable: '用脑过度者、饮食油腻者、爱美人士',
      element: '木',
      usage: '上投法：先注80°C水至七分满，再投入茶叶，待其徐徐下沉即可',
      storage: '密封冷藏保存（0-5°C），防潮防异味',
      taboo: '空腹不饮，胃寒者少量饮用',
      material: '碧螺春群体种',
      size: '净含量50g-200g',
      origin: '江苏苏州吴中区（国家地理标志产品）',
      certification: '国家地理标志产品·洞庭碧螺春',
      tags: ['名茶', '绿茶', '碧螺春']
    },
    // 乌龙茶
    {
      id: 'cy-003',
      categoryId: 'chayin',
      subcategoryId: 'wulong',
      name: '安溪铁观音（清香型）',
      image: '🍂',
      price: '结缘 168-888',
      rating: 4.8,
      sales: 12560,
      description: '安溪铁观音清香型，兰花香观音韵，七泡有余香，半发酵乌龙茶代表作',
      effects: '消食去腻、降脂减肥、提神益思、抗衰老',
      suitable: '饮食油腻者、减肥人士、茶道爱好者',
      element: '金',
      usage: '紫砂壶或盖碗：100°C沸水，7-8g茶叶，即冲即出，每泡递增5秒',
      storage: '密封阴凉干燥处保存，忌潮湿及异味',
      taboo: '空腹不饮浓茶，胃寒者少量饮用，孕妇减量',
      material: '铁观音品种（Camellia sinensis cv. Tieguanyin）',
      size: '净含量100g-500g',
      origin: '福建安溪（国家地理标志产品）',
      certification: '国家地理标志产品·安溪铁观音',
      tags: ['乌龙茶', '名茶', '铁观音']
    },
    {
      id: 'cy-004',
      categoryId: 'chayin',
      subcategoryId: 'wulong',
      name: '武夷大红袍（岩茶）',
      image: '🍂',
      price: '结缘 388-3888',
      rating: 4.9, premium: true,
      sales: 6543,
      description: '武夷山正岩产区大红袍，岩骨花香，醇厚回甘，乌龙茶之极品',
      effects: '消食解腻、降脂降压、提神醒脑、延缓衰老',
      suitable: '中老年人、饮食油腻者、品茗爱好者',
      element: '火',
      usage: '紫砂壶/盖碗：100°C沸水，8g茶叶，头泡浸润5秒醒茶倒掉，之后每泡15-30秒',
      storage: '密封阴凉干燥处保存，与湿度平衡，可长期存放愈陈愈香',
      taboo: '空腹不饮，失眠者晚间不饮，孕妇少量',
      material: '武夷岩茶大红袍品种',
      size: '净含量50g-250g',
      origin: '福建武夷山（国家地理标志产品）',
      certification: '国家地理标志产品·武夷岩茶',
      tags: ['乌龙茶', '岩茶', '大红袍']
    },
    // 黑茶普洱
    {
      id: 'cy-005',
      categoryId: 'chayin',
      subcategoryId: 'puer',
      name: '陈年普洱（勐海熟茶）',
      image: '🧱',
      price: '结缘 198-1988',
      rating: 4.8,
      sales: 8765,
      description: '云南勐海陈年普洱熟茶，渥堆发酵工艺，红浓明亮陈香醇厚，消食暖胃',
      effects: '消食去腻、暖胃养胃、降脂降压、润肠通便',
      suitable: '饮食油腻者、胃肠虚弱者、中老年人、养生人士',
      element: '水',
      usage: '紫砂壶/盖碗：100°C沸水，5-8g茶叶，润茶1-2次，之后每泡10-30秒可泡10泡以上',
      storage: '通风阴凉干燥处存放，忌潮湿及异味，可长期存放越陈越香',
      taboo: '胃酸过多者少量饮用，孕妇减量',
      material: '云南大叶种晒青毛茶',
      size: '净含量250g-1000g',
      origin: '云南西双版纳勐海',
      certification: '国家地理标志产品·普洱茶',
      tags: ['黑茶', '普洱', '消食暖胃']
    },
    // 白茶黄茶
    {
      id: 'cy-006',
      categoryId: 'chayin',
      subcategoryId: 'baicha',
      name: '福鼎白毫银针',
      image: '🌱',
      price: '结缘 288-1688',
      rating: 4.9, premium: true,
      sales: 5432,
      description: '福鼎太姥山白茶，采单芽制成，白毫满披如银似雪，毫香蜜韵清甜回甘',
      effects: '清热降火、抗氧化、降糖降脂、护肝明目',
      suitable: '上火体质、糖尿病患者、注重养生人士',
      element: '金',
      usage: '玻璃杯：85-90°C水温，3g茶叶，注水后静置2分钟即可，可反复冲泡5-6次',
      storage: '密封阴凉干燥处保存，忌潮湿及异味，可长期存放转化更醇',
      taboo: '胃寒者少量饮用或饭后饮用',
      material: '福鼎大白茶/大毫茶单芽',
      size: '净含量50g-250g',
      origin: '福建福鼎（国家地理标志产品）',
      certification: '国家地理标志产品·福鼎白茶',
      tags: ['白茶', '名茶', '白毫银针']
    },
    // 花茶养生茶
    {
      id: 'cy-007',
      categoryId: 'chayin',
      subcategoryId: 'huacha',
      name: '茉莉花茶（福州）',
      image: '🌸',
      price: '结缘 88-388',
      rating: 4.7,
      sales: 10234,
      description: '福州茉莉花茶，七窨一提工艺，绿茶吸花香，花茶茶花交融，香气鲜灵持久',
      effects: '理气解郁、安神助眠、清新口气、美颜养肤',
      suitable: '情绪低落者、失眠者、女性、日常饮品',
      element: '木',
      usage: '玻璃杯：85°C水温，3g茶叶，冲泡2-3分钟即可饮用',
      storage: '密封阴凉干燥处保存，忌阳光直射及异味',
      taboo: '胃寒者少量饮用',
      material: '绿茶茶坯+茉莉鲜花窨制',
      size: '净含量100g-300g',
      origin: '福建福州（国家地理标志产品）',
      certification: '国家地理标志产品·福州茉莉花茶',
      tags: ['花茶', '茉莉', '安神']
    },
    {
      id: 'cy-008',
      categoryId: 'chayin',
      subcategoryId: 'huacha',
      name: '陈皮普洱茶（新会柑普）',
      image: '🍊',
      price: '结缘 128-588',
      rating: 4.8,
      sales: 7890,
      description: '新会大红柑皮包裹勐海普洱熟茶，柑香茶醇，理气健脾润肺化痰',
      effects: '理气健脾、燥湿化痰、消食解腻、暖胃驱寒',
      suitable: '咳嗽痰多、消化不良、脾胃虚寒、烟酒过多者',
      element: '土',
      usage: '整颗冲泡或掰碎：100°C沸水，每次5-8g，润洗1次，每泡15-30秒',
      storage: '阴凉干燥处密封保存，忌潮湿，越陈越香',
      taboo: '气虚及阴虚燥咳者少量饮用',
      material: '新会陈皮+勐海普洱熟茶',
      size: '单颗重约25-40g，6-12颗装',
      origin: '广东新会/云南勐海',
      certification: '国家地理标志产品·新会陈皮',
      tags: ['花茶', '柑普', '理气']
    },

    // ═══════════════════════════════════════
    // ===== 干果零食 =====
    // ═══════════════════════════════════════
    // 坚果炒货
    {
      id: 'gg-001',
      categoryId: 'ganguo',
      subcategoryId: 'jiankang-hetao',
      name: '新疆纸皮核桃',
      image: '🥜',
      price: '结缘 48-188',
      rating: 4.8,
      sales: 15670,
      description: '新疆阿克苏薄皮核桃，壳薄如纸手捏即开，果仁饱满油脂丰富，补肾健脑',
      effects: '补肾固精、温肺定喘、润肠通便、健脑益智',
      suitable: '学生用脑、老人养生、孕妇补充营养、长期用电脑者',
      element: '土',
      usage: '直接手剥食用每日3-5颗，或入菜做核桃鸡丁、核桃粥',
      storage: '密封阴凉干燥处保存，可冷藏延长保存期',
      taboo: '阴虚火旺及腹泻者少量食用',
      material: '新疆阿克苏薄皮核桃',
      size: '净含量500g-2000g',
      origin: '新疆阿克苏',
      certification: '新疆名优特产',
      tags: ['坚果', '核桃', '健脑']
    },
    {
      id: 'gg-002',
      categoryId: 'ganguo',
      subcategoryId: 'jiankang-hetao',
      name: '长白山松子（红松籽）',
      image: '🌰',
      price: '结缘 68-268',
      rating: 4.7,
      sales: 8900,
      description: '长白山野生红松籽，颗粒饱满松脂香浓，润肺止咳滋阴润燥',
      effects: '润肺止咳、滋阴润燥、滑肠通便、延缓衰老',
      suitable: '肺燥咳嗽、皮肤干燥、便秘人群、中老年养生者',
      element: '金',
      usage: '开壳即食每日一小把（约15-20g），也可炒制松仁玉米、松仁糕点',
      storage: '密封冷藏保存（0-4°C），防潮防氧化',
      taboo: '脾虚便溏者少量食用',
      material: '红松（Pinus koraiensis）籽',
      size: '净含量250g-1000g',
      origin: '吉林长白山',
      certification: '国家地理标志产品·长白山松子',
      tags: ['坚果', '松子', '润肺']
    },
    // 养生干货
    {
      id: 'gg-003',
      categoryId: 'ganguo',
      subcategoryId: 'yangwei-ganhuo',
      name: '若羌红枣（特级）',
      image: '🫘',
      price: '结缘 38-128',
      rating: 4.8,
      sales: 22340,
      description: '新疆若羌灰枣，皮薄肉厚核小，自然吊干糖分凝结，补血养颜佳品',
      effects: '补中益气、养血安神、健脾和胃、美颜润肤',
      suitable: '气血两虚、月经不调、面色萎黄、脾胃虚弱者',
      element: '火',
      usage: '直接食用每日5-8颗，煮粥泡茶炖汤均可，宜与桂圆枸杞同炖',
      storage: '阴凉干燥处密封保存，防潮防虫',
      taboo: '湿盛脘腹胀满及糖尿病患者少量',
      material: '若羌红枣（Ziziphus jujuba）',
      size: '净含量500g-2000g',
      origin: '新疆若羌',
      certification: '国家地理标志产品·若羌红枣',
      tags: ['干货', '红枣', '补血']
    },
    {
      id: 'gg-004',
      categoryId: 'ganguo',
      subcategoryId: 'yangwei-ganhuo',
      name: '莆田桂圆干',
      image: '🟤',
      price: '结缘 48-168',
      rating: 4.7,
      sales: 12340,
      description: '福建莆田桂圆干，果大肉厚晶莹剔透，甘甜滋补，养心安神调失眠',
      effects: '补益心脾、养血安神、改善失眠、增强记忆',
      suitable: '失眠健忘、心悸怔忡、气血不足、产后体虚者',
      element: '火',
      usage: '直接食用每日5-10颗，煮粥炖汤配红枣枸杞，泡水饮用',
      storage: '密封阴凉干燥处保存，防潮防虫',
      taboo: '内有痰火及湿滞停饮者慎用',
      material: '莆田龙眼（Dimocarpus longan）',
      size: '净含量500g-1000g',
      origin: '福建莆田（国家地理标志产品）',
      certification: '国家地理标志产品·莆田桂圆',
      tags: ['干货', '桂圆', '安神']
    },
    {
      id: 'gg-005',
      categoryId: 'ganguo',
      subcategoryId: 'yangwei-ganhuo',
      name: '湘莲（去芯白莲子）',
      image: '⚪',
      price: '结缘 38-98',
      rating: 4.6,
      sales: 8760,
      description: '湖南湘潭寸三莲，去芯白莲子，粉糯香甜，养心安神健脾止泻',
      effects: '补脾止泻、益肾固精、养心安神、清心降火',
      suitable: '脾虚泄泻、心悸失眠、遗精带下、养生食疗者',
      element: '水',
      usage: '提前浸泡2-4小时，煮粥炖汤（配银耳/百合/红枣）',
      storage: '密封阴凉干燥处保存，防潮防虫',
      taboo: '中满痞胀及大便燥结者慎用',
      material: '湘莲（Nelumbo nucifera）去芯',
      size: '净含量250g-1000g',
      origin: '湖南湘潭（国家地理标志产品）',
      certification: '国家地理标志产品·湘莲',
      tags: ['干货', '莲子', '养心']
    },
    // 绿色特产
    {
      id: 'gg-006',
      categoryId: 'ganguo',
      subcategoryId: 'lvse-ganguo',
      name: '新疆葡萄干（吐鲁番）',
      image: '🍇',
      price: '结缘 28-88',
      rating: 4.6,
      sales: 18900,
      description: '吐鲁番无核白葡萄干，自然晾晒，颗粒均匀，清新甜润，天然能量补给',
      effects: '补气血、益肝肾、生津液、强筋骨',
      suitable: '贫血体虚、运动补充体能、办公零食',
      element: '火',
      usage: '直接食用每日一小把，也可加入面包/糕点/燕麦粥中',
      storage: '密封阴凉干燥处保存',
      taboo: '糖尿病患者少量食用',
      material: '无核白葡萄（Vitis vinifera）',
      size: '净含量250g-1000g',
      origin: '新疆吐鲁番',
      certification: '国家地理标志产品·吐鲁番葡萄干',
      tags: ['干果', '葡萄干', '新疆']
    },
    // 零嘴果脯
    {
      id: 'gg-007',
      categoryId: 'ganguo',
      subcategoryId: 'lingzhi-guo',
      name: '新会陈皮（十年陈）',
      image: '🍊',
      price: '结缘 68-388',
      rating: 4.8,
      sales: 7650,
      description: '广东新会十年自然陈化大红皮，外皮棕褐内囊浮松，理气健脾化痰圣品',
      effects: '理气健脾、燥湿化痰、消食开胃、降逆止呕',
      suitable: '脾胃气滞、咳嗽痰多、食积腹胀、晕车呕吐者',
      element: '土',
      usage: '泡水：撕小块沸水冲泡。煲汤：5g配猪肉/排骨慢炖。入药：遵医嘱',
      storage: '通风阴凉干燥处存放，每年检查翻晒防虫霉，越陈越佳',
      taboo: '气虚及阴虚燥咳者少量使用',
      material: '新会茶枝柑皮自然陈化',
      size: '净含量50g-250g',
      origin: '广东江门新会（国家地理标志产品）',
      certification: '国家地理标志产品·新会陈皮',
      tags: ['果脯', '陈皮', '理气', '陈年']
    },

    // ===== 工艺珍品 =====
    {
      id: 'gyp-001',
      categoryId: 'gongyipin',
      subcategoryId: 'yuqi',
      name: '和田玉平安扣',
      image: '💚',
      price: '结缘 388-3888',
      rating: 4.9, premium: true,
      sales: 3456,
      description: '新疆和田玉籽料精雕平安扣，玉质温润细腻，蕴君子之德，护出行平安',
      effects: '护佑平安、镇静安神、修身养德、以玉载道',
      suitable: '出行出差者、中老年人、传统文化爱好者、礼品馈赠',
      element: '土',
      usage: '佩戴于胸前或腰间，常以手盘养使其温润光泽',
      storage: '单独存放于软布袋中防划伤，忌与硬物碰撞',
      taboo: '忌化学洗涤剂清洗，避免高温暴晒',
      material: '新疆和田玉（Nephrite）',
      size: '直径2-5cm可选',
      origin: '新疆和田',
      certification: '国家地理标志产品·和田玉·鉴定证书',
      tags: ['玉器', '和田玉', '护佑']
    },
    {
      id: 'gyp-002',
      categoryId: 'gongyipin',
      subcategoryId: 'yuqi',
      name: '翡翠貔貅摆件',
      image: '💚',
      price: '结缘 688-8888',
      rating: 4.8,
      sales: 2345,
      description: '缅甸翡翠A货精雕貔貅，翡翠质地通透，貔貅纳财聚宝，镇宅招财',
      effects: '镇宅辟邪、招财纳福、增旺家运',
      suitable: '经商家庭、办公场所、新居乔迁、风水布局',
      element: '木',
      usage: '摆放于客厅财位或办公室桌面，貔貅头朝外以纳财',
      storage: '定期用软布擦拭，避免磕碰',
      taboo: '不可摆放卧室或卫生间，定期以清水冲洗去尘',
      material: '缅甸翡翠A货（Jadeite）',
      size: '高度8-20cm',
      origin: '缅甸进口/广东揭阳加工',
      certification: '国检翡翠A货鉴定证书',
      tags: ['玉器', '翡翠', '招财']
    },
    {
      id: 'gyp-003',
      categoryId: 'gongyipin',
      subcategoryId: 'taoci',
      name: '景德镇青花瓷茶具套装',
      image: '🏺',
      price: '结缘 288-1888',
      rating: 4.9, premium: true,
      sales: 5670,
      description: '景德镇手绘青花瓷茶具，蓝白相映水墨意境，千年窑火传承，品茗雅赏皆宜',
      effects: '提升审美修养、陶冶性情、传承中华瓷文化',
      suitable: '茶道爱好者、文化人士、高端礼品、居家装饰',
      element: '火',
      usage: '泡茶品茗，使用前以温水清洗预热，手洗为佳',
      storage: '摆放于通风干燥处，避免叠放碰撞',
      taboo: '忌微波炉加热，忌骤冷骤热以免开裂，忌钢丝球清洗',
      material: '高岭土/钴料手绘',
      size: '盖碗一套+品茗杯6只',
      origin: '江西景德镇（瓷都）',
      certification: '国家地理标志产品·景德镇瓷器',
      tags: ['陶瓷', '青花瓷', '茶具']
    },
    {
      id: 'gyp-004',
      categoryId: 'gongyipin',
      subcategoryId: 'taoci',
      name: '宜兴紫砂壶（名家手工）',
      image: '🫖',
      price: '结缘 588-5888',
      rating: 4.8,
      sales: 4321,
      description: '宜兴丁蜀镇原矿紫砂手工壶，泥色温润泡茶不夺香，养壶如养心',
      effects: '提升茶汤口感、修身养性、保值收藏',
      suitable: '茶道资深爱好者、收藏者、高端礼品',
      element: '土',
      usage: '专壶专茶（一种茶用一把壶），以茶水养壶以布擦壶逐步成包浆',
      storage: '独立摆放通风处，壶盖取下放置以免闷味',
      taboo: '忌用洗洁精清洗（会破坏包浆），忌骤冷骤热',
      material: '宜兴黄龙山原矿紫砂泥',
      size: '容量150ml-350ml',
      origin: '江苏宜兴丁蜀镇（国家地理标志产品）',
      certification: '国家地理标志产品·宜兴紫砂·手工艺人证书',
      tags: ['陶瓷', '紫砂', '收藏']
    },
    {
      id: 'gyp-005',
      categoryId: 'gongyipin',
      subcategoryId: 'sichou',
      name: '苏绣双面绣摆件',
      image: '🧵',
      price: '结缘 588-5888',
      rating: 4.9, premium: true,
      sales: 2345,
      description: '苏州镇湖苏绣大师手工双面绣，正反图案各异或相同，针法精细栩栩如生',
      effects: '提升家居格调、传承非遗文化、艺术收藏',
      suitable: '文化收藏家、国风家居装饰、高端礼品',
      element: '木',
      usage: '悬挂或立式摆放于客厅书房，避免强光直射',
      storage: '避光防尘，定期软毛掸去尘，不可水洗',
      taboo: '忌阳光直射以免丝线褪色，忌潮湿环境',
      material: '真丝底料/蚕丝线',
      size: '外框40x60cm至80x120cm',
      origin: '江苏苏州镇湖',
      certification: '国家级非物质文化遗产·苏绣传承人作品',
      tags: ['丝绸', '苏绣', '非遗']
    },
    {
      id: 'gyp-006',
      categoryId: 'gongyipin',
      subcategoryId: 'sichou',
      name: '杭州桑蚕丝丝巾',
      image: '🧣',
      price: '结缘 188-888',
      rating: 4.7,
      sales: 7890,
      description: '杭州100%桑蚕丝手工印花丝巾，质地柔滑光泽优雅，东方韵味尽显',
      effects: '提升气质、防晒护肤、展示文化品位',
      suitable: '女性日常穿搭、旗袍配饰、伴手礼',
      element: '木',
      usage: '可作围巾/披肩/头巾/包包装饰，多种系法',
      storage: '折叠收纳于丝巾盒中，忌重压',
      taboo: '忌机洗，宜干洗或手洗（冷水丝毛洗涤剂），忌拧绞',
      material: '100%桑蚕丝（Bombyx mori silk）',
      size: '90x90cm/110x110cm',
      origin: '浙江杭州（丝绸之府）',
      certification: '杭州丝绸原产地证明·桑蚕丝认证',
      tags: ['丝绸', '丝巾', '杭州']
    },
    {
      id: 'gyp-007',
      categoryId: 'gongyipin',
      subcategoryId: 'wenfang',
      name: '宣城宣笔（纯狼毫）',
      image: '🖊️',
      price: '结缘 88-688',
      rating: 4.8,
      sales: 3456,
      description: '安徽宣城宣笔厂纯狼毫毛笔，笔锋锐利弹性适中，书画皆宜',
      effects: '提升书画表现力、培养耐心修养、传承文房文化',
      suitable: '书法家、国画家、书画爱好者、学生',
      element: '木',
      usage: '开笔后以清水洗净濡墨，用后及时清洗挂起晾干',
      storage: '笔锋向下悬挂于笔架通风处，忌笔头长期浸水',
      taboo: '忌用后不洗使墨干结伤笔，忌笔头朝上插放',
      material: '黄鼠狼尾毫/竹杆',
      size: '出锋2-5cm可选',
      origin: '安徽宣城',
      certification: '国家级非物质文化遗产·宣笔制作技艺',
      tags: ['文房', '宣笔', '书法']
    },
    {
      id: 'gyp-008',
      categoryId: 'gongyipin',
      subcategoryId: 'wenfang',
      name: '歙砚（龙尾砚）',
      image: '🪨',
      price: '结缘 388-3888',
      rating: 4.8,
      sales: 2345,
      description: '江西婺源/安徽歙县龙尾砚，石质细腻发墨快，中国四大名砚之一',
      effects: '提升磨墨体验、欣赏石品纹理、文化收藏',
      suitable: '书画家、文房收藏家、高端礼品',
      element: '水',
      usage: '以水研墨，用后洗净砚面余墨保持砚面清洁',
      storage: '摆放于阴凉处，长期不用可涂薄层白蜡保护',
      taboo: '忌墨汁久留砚面以免浸损石质，忌摔碰',
      material: '龙尾石（歙砚石）',
      size: '长度15-30cm',
      origin: '江西婺源/安徽歙县',
      certification: '国家级非物质文化遗产·歙砚制作技艺',
      tags: ['文房', '歙砚', '砚台']
    },
    {
      id: 'gyp-009',
      categoryId: 'gongyipin',
      subcategoryId: 'baiwu',
      name: '东阳木雕摆件',
      image: '🪵',
      price: '结缘 388-3888',
      rating: 4.7,
      sales: 2345,
      description: '浙江东阳木雕手工精雕摆件，题材吉祥（松鹤延年等），榉木/樟木雕刻',
      effects: '传承非遗技艺、提升家居文化氛围、送礼有面',
      suitable: '传统文化爱好者、新居装饰、寿诞贺礼',
      element: '木',
      usage: '摆放于客厅博古架或玄关处，赏玩时忌用力触摸',
      storage: '避光避潮，定期软布拂尘，忌水洗',
      taboo: '忌阳光直射以免开裂，忌潮湿环境以免变形',
      material: '榉木/樟木手工雕刻',
      size: '高度20-60cm',
      origin: '浙江东阳',
      certification: '国家级非物质文化遗产·东阳木雕',
      tags: ['摆件', '木雕', '非遗']
    },
    {
      id: 'gyp-010',
      categoryId: 'gongyipin',
      subcategoryId: 'baiwu',
      name: '铜版画（传统手作）',
      image: '🖼️',
      price: '结缘 288-1888',
      rating: 4.6,
      sales: 1234,
      description: '传统铜版腐蚀工艺手作铜版画，山水花鸟/宗教题材，金属质感独特',
      effects: '装饰空间、提升品位、艺术收藏',
      suitable: '文艺爱好者、家居装饰、收藏者',
      element: '金',
      usage: '挂墙装饰，避免重物悬挂，定期软布轻拭',
      storage: '悬挂于避光处以免铜面氧化变色',
      taboo: '忌潮湿环境以免铜面生绿锈，忌化学清洁剂擦拭',
      material: '紫铜版/油墨',
      size: '画面尺寸30x40cm至60x80cm',
      origin: '云南大理',
      certification: '云南省工艺美术协会认证',
      tags: ['摆件', '铜版画', '工艺']
    },
    {
      id: 'gyp-011',
      categoryId: 'gongyipin',
      subcategoryId: 'baiwu',
      name: '手工漆器首饰盒',
      image: '🎁',
      price: '结缘 188-888',
      rating: 4.7,
      sales: 3210,
      description: '传统大漆工艺多层妆奁盒，黑底描金花开富贵，收纳首饰彰显品位',
      effects: '收纳美观、传承漆器文化、馈赠佳品',
      suitable: '女性自用、闺蜜礼物、婚嫁贺礼',
      element: '木',
      usage: '收藏首饰零碎，放置于梳妆台或展示柜',
      storage: '避光放置，保持干燥，忌重压',
      taboo: '忌阳光暴晒以免漆面开裂变色，忌化学溶剂擦拭',
      material: '实木胎/大漆/金粉描饰',
      size: '长度20-30cm，3-5层',
      origin: '福建福州',
      certification: '国家级非物质文化遗产·福州脱胎漆器技艺',
      tags: ['摆件', '漆器', '非遗']
    },
    {
      id: 'gyp-012',
      categoryId: 'gongyipin',
      subcategoryId: 'baiwu',
      name: '汝窑天青釉茶盏',
      image: '🫖',
      price: '结缘 168-888',
      rating: 4.8,
      sales: 4560,
      description: '仿宋代汝窑天青釉开片茶盏，雨过天青云破处之色，金丝铁线开片古雅',
      effects: '提升品茗仪式感、欣赏宋代名窑之美、雅致生活',
      suitable: '茶道爱好者、宋代文化爱好者、高端茶器收藏',
      element: '土',
      usage: '品茗专用，开片会随使用形成独特纹路变化',
      storage: '单独摆放避免碰撞，清洗后擦干存放',
      taboo: '忌微波炉加热，忌骤冷骤热，忌钢丝球清洗',
      material: '汝窑釉/高岭土',
      size: '容量100ml-200ml',
      origin: '河南汝州/江西景德镇',
      certification: '国家级非物质文化遗产·汝瓷烧制技艺',
      tags: ['陶瓷', '汝窑', '茶器']
    },
    // ===== 修行法器类 =====
    {
      id: 'fq-001',
      categoryId: 'fojia',
      subcategoryId: 'wisdom',
      premium: true,
      custom: true,
      name: '尼泊尔颂钵·七脉轮疗愈',
      image: 'https://images.unsplash.com/photo-1598518380437-8e2e8c5d5d5d?w=400&h=400&fit=crop',
      price: '结缘 268-1688',
      rating: 4.9, premium: true,
      sales: 356,
      origin: '尼泊尔加德满都',
      desc: '尼泊尔手工颂钵，七脉轮对应七种频率。敲击时产生持久共鸣音波，用于冥想入定、脉轮清理、空间净化、身心疗愈。',
      purpose: '冥想入定·脉轮清理·空间净化·身心疗愈',
      usage: '每日冥想前敲击3-7次，闭目感受音波振动遍满全身，逐个脉轮清理。亦可用于净宅、驱散负能量。',
      tags: ['颂钵', '冥想', '疗愈', '脉轮']
    },
    {
      id: 'fq-002',
      categoryId: 'fojia',
      subcategoryId: 'blessing',
      premium: true,
      custom: true,
      name: '老山檀木木鱼·诵经念佛',
      image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop',
      price: '结缘 128-888',
      rating: 4.8,
      sales: 523,
      origin: '老山（印度迈索尔）',
      desc: '老山檀木手工雕刻木鱼，声音清脆悦耳。诵经念佛时敲击节拍，摄心定念，帮助专注。檀木香气天然安神。',
      purpose: '诵经节拍·摄心定念·专注修行·安神定气',
      usage: '诵经念佛时手持木槌敲击，每句一击或每字一击，配合呼吸节奏。每日早晚课使用。',
      tags: ['木鱼', '诵经', '念佛', '檀木']
    },
    {
      id: 'fq-003',
      categoryId: 'daojia',
      subcategoryId: 'protect',
      name: '黄铜金刚铃杵·密宗法器',
      image: 'https://images.unsplash.com/photo-1598518380437-8e2e8c5d5d5d?w=400&h=400&fit=crop',
      price: '结缘 188-688',
      rating: 4.7,
      sales: 198,
      origin: '西藏拉萨',
      desc: '藏式黄铜金刚铃杵套装，铃声清越穿透。金刚铃代表智慧，金刚杵代表方便，二者合一为悲智双运。修法时摇铃可惊醒无明、召唤本尊。',
      purpose: '修法召唤·惊醒无明·悲智双运·驱邪护身',
      usage: '修法诵咒时右手摇铃，左手持杵。每次摇铃配合咒语节奏，修法前摇3声净场，修法后摇3声送圣。',
      tags: ['金刚铃', '金刚杵', '密宗', '法器']
    },
    {
      id: 'fq-004',
      categoryId: 'fojia',
      subcategoryId: 'wisdom',
      name: '水晶颂钵·高频净化',
      image: 'https://images.unsplash.com/photo-1598518380437-8e2e8c5d5d5d?w=400&h=400&fit=crop',
      price: '结缘 388-3688',
      rating: 5.0, premium: true,
      sales: 87,
      origin: '江西景德镇',
      desc: '高纯度水晶颂钵，声音纯净空灵，频率极高。比金属颂钵音波更细腻，适合深层净化、七脉轮对齐、空间能量场清理。',
      purpose: '深层净化·脉轮对齐·能量场清理·灵性提升',
      usage: '冥想前沿身体七个脉轮各敲击一次，让音波从头顶到脚底依次净化。每周1-2次深度清理。',
      tags: ['水晶颂钵', '净化', '脉轮', '高频']
    },
    {
      id: 'fq-005',
      categoryId: 'fojia',
      subcategoryId: 'blessing',
      name: '青铜磬·寺庙法器',
      image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop',
      price: '结缘 168-588',
      rating: 4.6,
      sales: 312,
      origin: '江西景德镇',
      desc: '青铜铸造法磬，声音悠远绵长。寺庙早晚课必备法器，诵经时击磬可摄受大众、通达三界。',
      purpose: '诵经摄众·通达三界·道场庄严·祈福通达',
      usage: '诵经开始前击磬一声，结束时击磬三声。亦可日常敲击净化空间，每次3-7声。',
      tags: ['磬', '法器', '寺庙', '净场']
    },
    {
      id: 'fq-006',
      categoryId: 'daojia',
      subcategoryId: 'health',
      name: ' Tibetan颂钵·大号疗愈',
      image: 'https://images.unsplash.com/photo-1598518380437-8e2e8c5d5d5d?w=400&h=400&fit=crop',
      price: '结缘 588-2688',
      rating: 4.9, premium: true,
      sales: 145,
      origin: '西藏拉萨',
      desc: '大号藏式颂钵（直径20cm+），音波浑厚深沉，穿透力强。适合全身疗愈、深层放松、引导入眠、集体冥想。',
      purpose: '全身疗愈·深层放松·引导入眠·集体冥想',
      usage: '疗愈时将颂钵置于身体各部位（七脉轮位置）敲击，让音波直接传导至体内。睡前敲7声助眠。',
      tags: ['颂钵', '大号', '疗愈', '入眠']
    },
    {
      id: 'fq-007',
      categoryId: 'fojia',
      subcategoryId: 'blessing',
      name: '电子木鱼·智能计数',
      image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop',
      price: '结缘 68-188',
      rating: 4.5,
      sales: 892,
      origin: '广东深圳',
      desc: '智能电子木鱼，自动计数念佛次数。支持木鱼声/铃声/磬声切换，音量可调。适合日常念佛计数，方便携带。',
      purpose: '念佛计数·日常修行·方便携带·随时诵念',
      usage: '念佛时轻敲电子木鱼，自动记录次数。每日目标108遍/1000遍，完成后可回向功德。',
      tags: ['电子木鱼', '计数', '念佛', '便携']
    },
    {
      id: 'fq-008',
      categoryId: 'daojia',
      subcategoryId: 'protect',
      premium: true,
      custom: true,
      name: '桃木剑·镇宅辟邪',
      image: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?w=400&h=400&fit=crop',
      price: '结缘 88-688',
      rating: 4.7,
      sales: 645,
      origin: '山东泰山',
      desc: '雷击桃木手工雕刻桃木剑，天然辟邪。桃木为五木之精，能压伏邪气。挂于门后或床头，镇宅辟邪，护佑家宅平安。',
      purpose: '镇宅辟邪·驱除邪煞·护佑家宅·门口悬挂',
      usage: '挂于大门后或卧室门后，剑尖朝下。亦可在感觉家宅不宁时手持桃木剑在各房间走一圈。',
      tags: ['桃木剑', '镇宅', '辟邪', '风水']
    }
  ],

  // 获取分类下的产品
  getProductsByCategory: function(categoryId) {
    return this.products.filter(p => p.categoryId === categoryId);
  },

  // 获取子分类下的产品
  getProductsBySubcategory: function(categoryId, subcategoryId) {
    return this.products.filter(p => p.categoryId === categoryId && p.subcategoryId === subcategoryId);
  },

  // 获取热门产品
  getHotProducts: function(limit = 10) {
    return [...this.products].sort((a, b) => b.sales - a.sales).slice(0, limit);
  },

  // 获取高评分产品
  getTopRatedProducts: function(limit = 10) {
    return [...this.products].sort((a, b) => b.rating - a.rating).slice(0, limit);
  }
};

// ===== 补充经典著作类商品的 origin 字段（名山大川来源）=====
(function() {
  var jingdianOrigins = {
    'ru-jing-001': '曲阜孔庙',
    'ru-jing-002': '曲阜孔庙',
    'ru-jing-003': '曲阜孔庙',
    'ru-jing-004': '曲阜孔庙',
    'ru-jing-005': '曲阜孔庙',
    'ru-jing-006': '嵩阳书院',
    'ru-jing-007': '曲阜孔庙',
    'ru-jing-008': '岳麓书院',
    'ru-jing-009': '岳麓书院',
    'ru-jing-010': '曲阜孔庙',
    'ru-jing-011': '白鹿洞书院',
    'dao-jing-001': '龙虎山',
    'dao-jing-002': '龙虎山',
    'dao-jing-003': '武当山',
    'dao-jing-004': '茅山',
    'dao-jing-005': '华山',
    'dao-jing-006': '武当山',
    'dao-jing-007': '罗浮山',
    'dao-jing-008': '青城山',
    'dao-jing-009': '龙虎山',
    'dao-jing-010': '白云观',
    'dao-jing-011': '武当山',
    'fo-jing-001': '五台山（文殊菩萨道场）',
    'fo-jing-002': '普陀山（观音道场）',
    'fo-jing-003': '九华山（地藏道场）',
    'fo-jing-004': '峨眉山（普贤道场）',
    'fo-jing-005': '少林寺',
    'fo-jing-006': '灵隐寺',
    'fo-jing-007': '法门寺',
    'fo-jing-008': '南华寺',
    'fo-jing-009': '法门寺',
    'fo-jing-010': '灵隐寺'
  };
  window.SHOP_DATA.products.forEach(function(p) {
    if (!p.origin && jingdianOrigins[p.id]) {
      p.origin = jingdianOrigins[p.id];
    }
    if (!p.origin) {
      p.origin = '全国';
    }
  });
})();

console.log('[shop-data.js] 已加载', window.SHOP_DATA.categories.length, '个分类，', window.SHOP_DATA.products.length, '个产品');
