'use strict';
(()=>{const $=id=>document.getElementById(id);let token=sessionStorage.getItem('clinical_token')||'',busy=false;const base=location.port==='8931'?'http://127.0.0.1:8932':'';
function state(){$('login').classList.toggle('hidden',!!token);$('work').classList.toggle('hidden',!token);}
async function api(path,body){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:body?JSON.stringify(body):undefined,signal:c.signal});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||'请求失败');return d;}finally{clearTimeout(t);}}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);$('message').textContent='正在处理…';try{await fn();$('message').textContent='已完成';}catch(e){$('message').textContent=e.name==='AbortError'?'请求超时，请刷新确认后重试':e.message;}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);state();}}
function add(p,t,s){const e=document.createElement(t);e.textContent=s;p.append(e);return e;}
async function list(){const d=await api('/api/knowledge-review/entries');$('entries').replaceChildren();for(const e of d.items){const a=add($('entries'),'article','');add(a,'h3',e.title);add(a,'p',e.content);add(a,'small',e.status+' · '+e.evidence.map(x=>x.source_id+' '+x.locator+' '+x.version).join('；'));for(const action of e.status==='pending_review'?['approve','reject']:e.status==='formal'?['revoke']:[]){const b=add(a,'button',({approve:'审核发布',reject:'驳回',revoke:'撤回'})[action]);b.onclick=()=>run(async()=>{await api('/api/knowledge-review/entries/'+e.id+'/action',{action,revision:e.revision,reason:$('reason').value,deidentified:$('deidentified').checked,rights_verified:$('rights').checked,evidence_verified:$('evidence').checked});await list();});}}}
$('sourceSearch').onclick=()=>run(async()=>{const d=await api('/api/knowledge-review/source-evidence?q='+encodeURIComponent($('sourceQuery').value));$('sourceResults').replaceChildren();for(const e of d.items){const a=add($('sourceResults'),'article','');add(a,'p',e.content);add(a,'small',e.evidence.map(x=>x.source_id+' · '+x.locator+' · '+x.file_sha256).join('；'));}for(const e of d.professional_sources){const a=add($('sourceResults'),'article','');add(a,'h3',e.title);add(a,'p',e.distilled_summary);const l=add(a,'a','查看专业源头');l.href=e.url;l.target='_blank';l.rel='noopener noreferrer';}if(!d.items.length&&!d.professional_sources.length)add($('sourceResults'),'p','暂无匹配证据，请调整关键词。');});
$('loginForm').onsubmit=e=>{e.preventDefault();run(async()=>{const d=await api('/api/auth/login',Object.fromEntries(new FormData(e.target)));token=d.token;sessionStorage.setItem('clinical_token',token);e.target.reset();await list();});};$('entryForm').onsubmit=e=>{e.preventDefault();run(async()=>{const f=Object.fromEntries(new FormData(e.target));await api('/api/knowledge-review/entries',{title:f.title,content:f.content,syndrome:f.syndrome,evidence:[{source_id:f.source_id,locator:f.locator,version:f.version}]});e.target.reset();await list();});};$('refresh').onclick=()=>run(list);$('logout').onclick=()=>{token='';sessionStorage.removeItem('clinical_token');$('entries').replaceChildren();$('sourceResults').replaceChildren();state();};state();if(token)run(list);
})();
